### ISSUE TITLE
这个错误是由于使用了不支持的功能（embeddings）而导致的请求被限制。GPT-3.5-turbo 引擎不支持嵌入功能。[Enhancement]

### ISSUE THREAD

**Issue by zxyy123** [chatanywhere/GPT_API_free#102]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chatanywhere** [comment]
接口使用错误，请仔细阅读接口文档
