### ISSUE TITLE
gpt-3.5-turbo-instruct 费用问题

### ISSUE THREAD

**Issue by jian53286** [chatanywhere/GPT_API_free#104]
open ai 对gpt-3.5-turbo-instruct定价与gpt-3.5-turbo 4k 相同
<img width="1497" alt="截屏2023-10-06 15 56 02" src="https://github.com/chatanywhere/GPT_API_free/assets/118868907/71187e9f-8e1b-4942-8db6-8199f332ac0a">

但chatanywhere扣费如下，比gpt-3.5-turbo 4k高出很多，这是为什么呢？

<img width="904" alt="截屏2023-10-06 15 59 12" src="https://github.com/chatanywhere/GPT_API_free/assets/118868907/d14f679e-4f1c-4b50-9ca4-e7ca8a592bd2">

**Comment by chatanywhere** [comment]
已修复，之前是直接按照了davinci003的标准扣费的，现在已经调整到和gpt-3.5-turbo扣费标准一致。
