### ISSUE TITLE
Zotero-pdf-translate中关于GPT翻译使用问题

### ISSUE THREAD

**Issue by Komorebi-yaodong** [chatanywhere/GPT_API_free#110]
**Describe the bug 描述bug**
不论是用`https://api.chatanywhere.com.cn/v1`还是`https://api.chatanywhere.com.cn`都会产生405错误

**To Reproduce 复现方法**
1. 打开zotero（安装好了zotero-pdf-translate）
2. 进行首选项中翻译选项中GPT翻译的配置
3. 保存配置后划词翻译
4. 出现报错

**Screenshots 截图**
![image](https://github.com/chatanywhere/GPT_API_free/assets/84176918/3ed1119e-b67a-4b77-b6aa-90b21415e4c8)

**Tools or Programming Language 使用的工具或编程语言**
None

**Additional context 其他内容**
报错内容如下
```
[请求错误]

此翻译引擎不可用，可能是密钥错误，也可能是请求过快。
可以尝试其他翻译引擎，或者来此查看相关回答：
https://zotero.yuque.com/staff-gkhviy/pdf-trans/age09f 

请注意，这些错误与 Zotero 和本翻译插件无关，由该翻译服务引起： GPT🗝️

Error: HTTP POST https://api.chatanywhere.com.cn failed with status code 405:

<html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by weiSENshu** [comment]
出现同上问题，不知如何解决。使用zoteroGPT时，API可以正常使用

**Comment by lijiehao1** [comment]
出现同上问题，不知如何解决。使用zoteroGPT时，API可以正常使用

**Comment by lyly1122** [comment]
同样的问题

**Comment by LiSonglin-xidian** [comment]
同样的问题~

**Comment by chatanywhere** [comment]
接口配置有误，应该设置为https://api.chatanywhere.tech/v1/chat/completions
<img width="216" alt="image" src="https://github.com/chatanywhere/GPT_API_free/assets/111742565/4bd19f24-e7ad-4d01-85f2-2898731a67d0">
