### ISSUE TITLE
API_BASE 连接问题

### ISSUE THREAD

**Issue by sxzhang2009** [chatanywhere/GPT_API_free#112]
错误信息
----------
API Error: {"object":null,"data":null,"error":{"message":"OpenAI response error","type":"cf_bad_gateway","param":null,"code":"502"}}

试过 https://api.chatanywhere.com.cn 和 api.chatanywhere.cn 两个域名，都不行，这两个API用了2个多月了，除了有点不稳定之外，平常没有其他问题。 10/20日（今天）开始连不上了。

**Comment by BunnySakura** [comment]
同上，连不上了

**Comment by chatanywhere** [comment]
![image](https://github.com/chatanywhere/GPT_API_free/assets/111742565/92427d9f-e195-4ad6-bf82-68972a4135ca)
https://status.openai.com/
官方炸了几个小时了，可以查看官方公告

**Comment by jiayu-zh** [comment]
同上今天开始连不上了，显示的是key status is invalid

**Comment by BitbanChou** [comment]
现在可以了吗？

**Comment by chatanywhere** [comment]
早就好了
