### ISSUE TITLE
Bug：APIError: OpenAI response error -the api seems not stable？

### ISSUE THREAD

**Issue by Siki-cloud** [chatanywhere/GPT_API_free#113]
**Describe the bug 描述bug**

I got the _JSONDecodeError_  and _APIERROR_  when calling the api.   I dont knew why, can anyone help me?

**APIError:** OpenAI response error {"object":null,"data":null,"error":{"message":"OpenAI response error","type":"auth_subrequest_error","param":null,"code":"internal_error"}} 500 {'object': None, 'data': None, 'error': {'message': 'OpenAI response error', 'type': 'auth_subrequest_error', 'param': None, 'code': 'internal_error'}} {'Date': 'Fri, 20 Oct 2023 02:53:55 GMT', 'Content-Type': 'application/json', 'Content-Length': '139', 'Connection': 'keep-alive', 'access-control-allow-credentials': 'true', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'OPTIONS,GET,POST', 'access-control-allow-headers': '*', 'access-control-max-age': '6000', 'vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'CF-Cache-Status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=l9WcgN%2BdxK1%2Ff39hiGvr19stlLkH0LtpbJTEYkOiBW6V2CmeI2SFDyTYB3j6WWEGWQ76ySZmu4XGanBsw211zwnAMrlq9upj%2Bg2mgA6LxWStBmU%2FmEd7g8htk1%2B%2F0k6x9CgBjiuN"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'CF-RAY': '818df902cc9c410a-SIN'}  

**To Reproduce 复现方法**
```python

BASE_URL = "https://api.chatanywhere.cn/v1"
API_KEY = "sk-XXXXXXXXXXXXXXXX"
openai.api_base = BASE_URL
openai.api_key = API_KEY
GLOBAL_MODEL = "gpt-3.5-turbo"

cf_num=10
query_instance = "Widow hires a psychopath as a handyman. Sloppy film noir thriller which doesn't make much of its tension promising set-up."
# ask gpt
promt = (f'i got a opinion about a movie: {query_instance}.\n'
             f'i want to {cf_num} different sentences to express the opposite sentiment')

chat_completion = openai.ChatCompletion.create(
        model=GLOBAL_MODEL,
        messages=[{"role": "user", "content": promt}])
# print(chat_completion)
answer = chat_completion['choices'][0]["message"]['content']
print(answer)
``` 

when i set cf_num=10/20/30, it return the right answer. but setting cf_cum >=50, it raises the APIError. 

 I dont knew why, can anyone help me?

**Screenshots 截图**

This is my error traceback. It appears to be inconvenient to paste my screenshot.

JSONDecodeError                           Traceback (most recent call last)
File D:\anaconda3\envs\polyjuice-py38\lib\site-packages\openai\api_requestor.py:673, in APIRequestor._interpret_response_line(self, rbody, rcode, rheaders, stream)
    672     else:
--> 673         data = json.loads(rbody)
    674 except (JSONDecodeError, UnicodeDecodeError) as e:

File D:\anaconda3\envs\polyjuice-py38\lib\json\__init__.py:357, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    354 if (cls is None and object_hook is None and
    355         parse_int is None and parse_float is None and
    356         parse_constant is None and object_pairs_hook is None and not kw):
--> 357     return _default_decoder.decode(s)
    358 if cls is None:

File D:anaconda3\envs\polyjuice-py38\lib\json\decoder.py:337, in JSONDecoder.decode(self, s, _w)
    333 """Return the Python representation of ``s`` (a ``str`` instance
    334 containing a JSON document).
    335 
    336 """
--> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338 end = _w(s, end).end()

File D:\anaconda3\envs\polyjuice-py38\lib\json\decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

APIError                                  Traceback (most recent call last)

**Tools or Programming Language 使用的工具或编程语言**
python3.8 

**Additional context 其他内容**

**Comment by chatanywhere** [comment]
![image](https://github.com/chatanywhere/GPT_API_free/assets/111742565/543faf31-f241-46eb-8ccb-c42e34775bc5)
https://status.openai.com/
