### ISSUE TITLE
hosts

### ISSUE THREAD

**Issue by zhou20120904** [chatanywhere/GPT_API_free#114]
可以把hosts文件里的api.openai.com的ip改成api.chatanywhere.com.cn的吗？

**Comment by zhou20120904** [comment]
这样子说不定遇到改不了baseurl的项目就可以了

**Comment by chatanywhere** [comment]
不会有用的 hosts文件只支持域名到ip的映射 不支持域名到域名的映射

**Comment by zhou20120904** [comment]
我是说ping一下，获取ip之后再映射

**Comment by zhou20120904** [comment]
> 不会有用的 hosts文件只支持域名到ip的映射 不支持域名到域名的映射

我是说ping一下，获取ip之后再映射

**Comment by chatanywhere** [comment]
也是不可以的哈

**Comment by zhou20120904** [comment]
> 也是不可以的哈

哦
