### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by MikeMcKayq** [chatanywhere/GPT_API_free#116]
在web.chatboxai中无法使用，显示下列内容，并且api无法调用。
API Error: {"error":{"code":"license_inactived","detail":"License Inactived","status":401,"title":"License Inactived"}}

An error has occurred with Chatbox-AI, which is usually caused by incorrect settings or account issues. Please check your AI settings and account status, or click here to view the FAQ document.
大概是上半年用过，当时使用正常，中间有几个月没有使用，这几天发现无法使用，访问转发Host1显示如下，Host2可正常访问。
401  需要授权
此服务器无法验证您是否有权访问请求的文档。

由Tengine提供动力

**Comment by xixiaoguai727** [comment]
我也是同样的情况

**Comment by ynpl** [comment]
前几天openai 出问题了
