### ISSUE TITLE
请问最新2.2.1版本在哪里修改api.chatanywhere.com.cn，找不到openai_client.js文件了

### ISSUE THREAD

**Issue by morefiish** [chatanywhere/GPT_API_free#117]

**Comment by lorcan-cloud** [comment]
直接搜索整个文件夹中的 api.openai.com，然后替换为 api.chatanywhere.com.cn
![image](https://github.com/chatanywhere/GPT_API_free/assets/65481101/2f47ce6f-d150-4f88-a427-b92c3e815104)
