### ISSUE TITLE
免费的api key额度使用完毕后，只能购买充值额度？

### ISSUE THREAD

**Issue by tangtao-xp1** [chatanywhere/GPT_API_free#119]
使用了下，确实很方便很好用。

在轻度试用免费的api key一个周以后，api接口报错：

API Error: {"object":null,"data":null,"error":{"message":"OpenAI response error","type":"insufficient_quota","param":null,"code":"insufficient_quota"}}

应该是额度使用完毕。那么是否会自动帮扩充额度，还是需要我们充值购买额度，谢谢！

**Comment by chatanywhere** [comment]
这个报错不管就行，可能后台有一个号挂了
