### ISSUE TITLE
请问如何设置等待超时

### ISSUE THREAD

**Issue by fitzhang** [chatanywhere/GPT_API_free#126]
def gpt_35_api_stream(messages: list):
try:
response = openai.ChatCompletion.create(
model='gpt-3.5-turbo',
messages=messages,
stream=True,
)
completion = {'role': '', 'content': ''}
for event in response:
if event['choices'][0]['finish_reason'] == 'stop':
break
for delta_k, delta_v in event['choices'][0]['delta'].items():
completion[delta_k] += delta_v
messages.append(completion) # 直接在传入参数 messages 中追加消息
return (True, '')
except Exception as err:
return (False, f'OpenAI API 异常: {err}')

**Comment by fitzhang** [comment]
以上代码中，某些问题需要等待很久才嗯那个回复，请问如何设置等待超时的时间 谢谢！

**Comment by chatanywhere** [comment]
编码问题可以百度一下
