### ISSUE TITLE
Open access for gpt4-turbo

### ISSUE THREAD

**Issue by xsw1208** [chatanywhere/GPT_API_free#127]
hello, it is a good repository for Chinese. When will you open access for gpt-4v or gpt4-turbo?

**Comment by mmwong1984** [comment]
ALMOST NENVER, AND GPT-3.5 OF THIS API IS SEEMS DEAD...

**Comment by chatanywhere** [comment]
ChatAnywhere already supports gpt-4-1106-preview, but gpt-4-v will have to wait a while for support.
