### ISSUE TITLE
买了，但在chatbox中，为啥回答不像是gpt-4？

### ISSUE THREAD

**Issue by KngJmmy** [chatanywhere/GPT_API_free#13]
![image](https://github.com/chatanywhere/GPT_API_free/assets/123545513/7ab47286-2c04-437e-b0c6-46c1b232a5c4)
而我在官网渠道，同样是gpt-4模型，答复完全不同！
<img width="1266" alt="image" src="https://github.com/chatanywhere/GPT_API_free/assets/123545513/23364ce6-c626-4712-92cc-fa17fb09657a">

**Comment by chatanywhere** [comment]
参考#8 
1. API和官方网页不同，原版的API是不知道自己是什么版本的GPT的，因为训练数据集到2021年9月，所以它只会回答自己是GPT3。想要它回答自己是GPT4很简单，加前置prompt。
2. 测试问题大部分都可以按照期望回答正确的结果，但大模型本就有很大的不确定性，另外调用api的参数不同也会影响结果，所以gpt4如果有个别问题没有按照预期回答也是很正常的。如果我想造假很简单，gpt3.5+前置prompt就行了，但这边都是不对用户发出的数据和官方返回的数据做任何处理的，所以实在有疑问请去找openai官方。
3. 自己平时使用中自行体验，真的假不了，假的真不了。
