### ISSUE TITLE
GPT-4-1106-PREVIEW	价格好像比较贵。官网0.08不到的input

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [chatanywhere/GPT_API_free#133]
GPT-4-1106-PREVIEW	价格好像比较贵。官网0.08不到的input

**Comment by chatanywhere** [comment]
是的，因为我们拿到的preview每日用量有限，为了相对减少使用，我们暂时没有降低gpt-4-preview的价格，在官方彻底开放后我们会跟随官方降价

**Comment by liuhuapiaoyuan** [comment]
不管怎么样 都是良心价

**Comment by chatanywhere** [comment]
官方给了我们更多的调用次数，已经降价了，比官方便宜了
