### ISSUE TITLE
gpt acdemic 显示非OpenAI官方接口返回了错误:wrong api key

### ISSUE THREAD

**Issue by zzw1210** [chatanywhere/GPT_API_free#136]
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://api.chatanywhere.com.cn/v1/chat/completions"}已经改了
然后用gpt4，显示非OpenAI官方接口返回了错误:wrong api key，如何解决？

**Comment by chatanywhere** [comment]
大概率key错了

**Comment by yuzhou01** [comment]
哥们，一样的情况，后来你是怎么解决的？

> API_URL_REDIRECT = {“https://api.openai.com/v1/chat/completions”： “[https://api.chatanywhere.com.cn/v1/chat/completions”}已经改](https://api.chatanywhere.com.cn/v1/chat/completions%22%7D%E5%B7%B2%E7%BB%8F%E6%94%B9%E4%BA%86)了 然后用gpt4，显示非OpenAI官方接口返回了错误：wrong api key，如何解决？

![微信图片编辑_20231120184443](https://github.com/chatanywhere/GPT_API_free/assets/96414333/625b1302-bfbb-4f1a-806a-96e0530226c3)

**Comment by wswbx** [comment]
所以咋办，我也是用这个显示密钥错误

**Comment by zzw1210** [comment]
多刷新几遍，并没有很好的办法




张臻玮
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatanywhere/GPT_API_free"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月15日(星期五) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatanywhere/GPT_API_free] gpt acdemic 显示非OpenAI官方接口返回了错误:wrong api key (Issue #136)





 
所以咋办，我也是用这个显示密钥错误
