### ISSUE TITLE
大大您好请问429报错是什么原因呢

### ISSUE THREAD

**Issue by lzlbeijing** [chatanywhere/GPT_API_free#138]
too many requests 这类问题请问如何解决

**Comment by chatanywhere** [comment]
> 免费API Key限制60请求/小时/IP&Key调用频率，也就是说你如果在一个IP下使用多个Key，所有Key的每小时请求数总和不能超过60；同理，你如果将一个Key用于多个IP，这个Key的每小时请求数也不能超过60。(付费版API没有这个限制)
