### ISSUE TITLE
Network Error: Failed to fetch

### ISSUE THREAD

**Issue by yansheng836** [chatanywhere/GPT_API_free#139]
**Describe the bug 描述bug**

Network Error: Failed to fetch

**To Reproduce 复现方法**

1.配置了这里免费的key
2.配置了host

Network Error: Failed to fetch

网络错误。请检查当前的网络状态，以及与 https://api.openai.com 的连接情况。因为你设置了代理地址 https://api.chatanywhere.com.cn，请检查代理服务器是否正常工作，或者考虑在设置中删除代理地址。

**Screenshots 截图**
![image](https://github.com/chatanywhere/GPT_API_free/assets/45334066/659eeb74-185d-4ba4-90b5-d928fbec5b13)

**Tools or Programming Language 使用的工具或编程语言**
chatbox  当前最新版 1.1.4

**Comment by chatanywhere** [comment]
设置有误，请仔细阅读readme
