### ISSUE TITLE
For the same token, GPT 4 throws 403 error

### ISSUE THREAD

**Issue by Matthewow** [chatanywhere/GPT_API_free#140]
<img width="751" alt="image" src="https://github.com/chatanywhere/GPT_API_free/assets/41960338/cc64e008-9166-468a-bf07-d2b90d9b6b13">

For the same token, GPT 4 throws a 403 error, while GPT 3.5 does not.

**Comment by chatanywhere** [comment]
If you are using a free key, the free one does not support gpt-4.
If you are using a paid key, it may be because the account balance is less than 0.8.

**Comment by Matthewow** [comment]
Thanks @chatanywhere for quick replying, the balance is indeed less than 0.8.
