### ISSUE TITLE
Support "gpt-4-visual-preview" [Enhancement]

### ISSUE THREAD

**Issue by alex374** [chatanywhere/GPT_API_free#145]
目前 [chat completion](https://platform.openai.com/docs/api-reference/chat/create) 接口不支持图片上传
<img width="1425" alt="image" src="https://github.com/chatanywhere/GPT_API_free/assets/10289841/dfc5b549-8bd1-4228-be2e-e7f07629b574">
<img width="1248" alt="image" src="https://github.com/chatanywhere/GPT_API_free/assets/10289841/bcf38d02-2922-4081-b69d-35a971937ad8">

**Comment by chatanywhere** [comment]
官方preview阶段该模型我们一天只有100次调用次数，无法公开使用，等官方开放后我们会支持

**Comment by chatanywhere** [comment]
现在已经支持了
