### ISSUE TITLE
zoteroGPT突然不能用了 这是为啥

### ISSUE THREAD

**Issue by Drewhhh** [chatanywhere/GPT_API_free#147]
![Snipaste_2023-11-25_15-55-49](https://github.com/chatanywhere/GPT_API_free/assets/148340483/bb55be75-0f09-4de9-9d7f-7d73a20b1144)
zoteroGPT突然不能用了 这是为啥

**Comment by psychech** [comment]
同问。
什么原因导致在zotero gpt中无法阅读pdf了？

**Comment by chatanywhere** [comment]
提供的错误信息太少，无法提供解答
