### ISSUE TITLE
1106好像没有支持openai的json接口

### ISSUE THREAD

**Issue by bernardx** [chatanywhere/GPT_API_free#149]
**Describe the bug 描述bug**
官方的gpt-3.5-turbo-1106 支持返回json格式，但是这里好像没有支持

文档在这里 `https://platform.openai.com/docs/guides/text-generation/json-mode`

请求后报错：openai.APIStatusError: Error code: 307

**Comment by chatanywhere** [comment]
这边测试没有问题，请检查其他问题，或者提交更具体的错误日志

**Comment by chatanywhere** [comment]
<img width="1053" alt="image" src="https://github.com/chatanywhere/GPT_API_free/assets/111742565/ee9544fa-0963-4f7d-bc53-8cfc7d4d0f89">

**Comment by bernardx** [comment]
感谢快速反馈，这边之前是用python api访问的，是sdk版本老了，更新后已经正常。
