### ISSUE TITLE
购买key后，openai python库的使用过程中出现连接错误

### ISSUE THREAD

**Issue by 180808118** [chatanywhere/GPT_API_free#153]
> 已经在代码中加入了openai.api_base = "https://api.chatanywhere.com.cn"
整个代码如下

```
client = OpenAI(
    # defaults to os.environ.get("OPENAI_API_KEY")
    api_key="sk-",
)

def get_completion(prompt, model='gpt-3.5-turbo'):
    messages = [{'role': "user", "content": prompt}]
    response = client.chat.completions.create(model=model, messages=messages, temperature=0,
                                            presence_penalty=0.0,
                                            frequency_penalty=0.0)
    return response.choices[0].message['content']

if __name__ == '__main__':
    prompt = ["The following is a conversation between two friends, John and Sarah.",
              "John: Hi Sarah, how are you doing today?",
              "Sarah: I'm doing great, thanks for asking. How about you?",
              "John: I'm doing pretty well too. So, did you hear about the new restaurant that just opened up downtown?"]
    get_completion(prompt)
```

但是运行该文件时仍旧报错：
![image](https://github.com/chatanywhere/GPT_API_free/assets/67565706/31231ccf-aaf8-4992-991c-f3444d3958a8)

**Comment by ynpl** [comment]
新版openai 库的调用方式不一样了
from openai import OpenAI

client = OpenAI(
    # 输入转发API Key
    api_key="sk-xxxxxxx",
    base_url="https://api.chatanywhere.com.cn/v1"
)

completion = client.chat.completions.create(
    model="gpt-3.5-turbo-1106",
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "你是谁!"}
    ],
    stream=True  # 是否开启流式输出
)

# 非流式输出获取结果
# print(completion.choices[0].message)
# 流式输出获取结果
for chunk in completion:
    print(chunk.choices[0].delta)

**Comment by ynpl** [comment]
新版的openai库方法变了
`from openai import OpenAI

client = OpenAI(
    # 输入转发API Key
    api_key="sk-xxxxxxx",
    base_url="https://api.chatanywhere.com.cn/v1"
)

completion = client.chat.completions.create(
    model="gpt-3.5-turbo-1106",
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "你是谁!"}
    ],
    stream=True  # 是否开启流式输出
)

# 非流式输出获取结果
# print(completion.choices[0].message)
# 流式输出获取结果
for chunk in completion:
    print(chunk.choices[0].delta)
`

**Comment by 180808118** [comment]
***@***.******@***.***的问题咨询邮件，因为邮件内容一部分是相同的问题，另一部分已解决。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatanywhere/GPT_API_free"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月15日(星期五) 上午10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatanywhere/GPT_API_free] 购买key后，openai python库的使用过程中出现连接错误 (Issue #153)





 
新版的openai库方法变了
 `from openai import OpenAI
 
client = OpenAI(
 # 输入转发API Key
 api_key="sk-xxxxxxx",
 base_url="https://api.chatanywhere.com.cn/v1"
 )
 
completion = client.chat.completions.create(
 model="gpt-3.5-turbo-1106",
 messages=[
 {"role": "system", "content": "You are a helpful assistant."},
 {"role": "user", "content": "你是谁!"}
 ],
 stream=True  # 是否开启流式输出
 )
 
非流式输出获取结果
 
print(completion.choices[0].message)
 
流式输出获取结果
 
for chunk in completion:
 print(chunk.choices[0].delta)
 `
