### ISSUE TITLE
免费的gpt-4不是gpt-4 是3

### ISSUE THREAD

**Issue by ZhuJD-China** [chatanywhere/GPT_API_free#154]

**Comment by chatanywhere** [comment]
是gpt-4，不可能是3哈，百度一下4和3的区别自己测试一下

**Comment by dadaoerv** [comment]
![8073d55cf944419bf4dba9f8d7dc540b](https://github.com/chatanywhere/GPT_API_free/assets/46274596/c51c7965-6f10-4297-b6ee-d1cddd5afd8a)

**Comment by chatanywhere** [comment]
> ![8073d55cf944419bf4dba9f8d7dc540b](https://private-user-images.githubusercontent.com/46274596/293293838-c51c7965-6f10-4297-b6ee-d1cddd5afd8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MjA2MTUsIm5iZiI6MTcwMzgyMDMxNSwicGF0aCI6Ii80NjI3NDU5Ni8yOTMyOTM4MzgtYzUxYzc5NjUtNmYxMC00Mjk3LWI2ZWUtZDFjZGRkNWFmZDhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDAzMjUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZmZmMjgyNDI0ZWVlNzViZjk1MDU0M2NhYzA2ZGJlNzY1ZDFmNmFhMzNlZmFjMzE4MWQyYmViN2U5YzZmOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DHLpjxTm8AF9RYuD8fn5lAwAnE7UEJef4cAC74qGM0Q)

检查一下你使用软件的前置prompt，这是你使用的软件或者插件设置的前置prompt让gpt回答的自己是gpt-3.5-turbo，实际上不管是gpt-3.5-turbo还是gpt-4只会回答自己是“gpt-3”，这些其实你网上搜一下就知道。
