### ISSUE TITLE
请问一下，免费的API，AMA是否不支持gpt-4-vision

### ISSUE THREAD

**Issue by xugh1997** [chatanywhere/GPT_API_free#155]
感谢作者大大的无私分享和辛苦付出，问题截图如下：
![gpt-vison](https://github.com/chatanywhere/GPT_API_free/assets/148083688/e5b46f9a-22be-4cc3-be91-8ce5daebfc1f)

**Comment by xugh1997** [comment]
AMA就是作者大大在readme里面提到的ChatGPT桌面应用BotGem

**Comment by loukai99** [comment]
是的 免费的不支持gpt-4-v 付费版支持

**Comment by xugh1997** [comment]
> 是的 免费的不支持gpt-4-v 付费版支持

好的，多谢
