### ISSUE TITLE
请问一下，Zotero Translate按照教程里配置之后，翻译出来的文本不对

### ISSUE THREAD

**Issue by 1OZ4** [chatanywhere/GPT_API_free#159]
![PixPin_2023-12-19_18-17-26](https://github.com/chatanywhere/GPT_API_free/assets/59152371/62550554-3dda-4e79-a8b4-7969e0ce94da)
请问一下，Zotero Translate按照教程里配置之后，翻译出来的文本不对，感觉像是再向gpt提问，而不是翻译

**Comment by ynpl** [comment]
那你应该联系zotero的开发者

**Comment by CellLz** [comment]
对pdf进行翻译的难点在于从pdf里把格式不统一的文字提取出来，所以对于pdf的翻译最好是能找到这篇论文的网页版，然后用沉浸式翻译进行翻译，这样准确率会高出很多。
