### ISSUE TITLE
使用沉浸式翻译无法翻译

### ISSUE THREAD

**Issue by istraw** [chatanywhere/GPT_API_free#160]
用的是免费账号
<img width="789" alt="image" src="https://github.com/chatanywhere/GPT_API_free/assets/6996725/4d4793f8-27e8-4059-a2d0-afba54b07d11">
设置后，点测试
<img width="805" alt="image" src="https://github.com/chatanywhere/GPT_API_free/assets/6996725/e2903e2a-b7d6-4048-90d7-85e0022b7bb6">
不管开不开代理都不行，实际使用也翻译不出，用其他软件填入key和地址可以正常使用gpt对话。
请帮忙看看，是我哪里设置不对？

**Comment by chatanywhere** [comment]
我这边测试沉浸式翻译没有遇到你所遇到的问题，配置项看起来也没有问题，建议可以检查一下浏览器的代理网络配置

**Comment by istraw** [comment]
> 我这边测试沉浸式翻译没有遇到你所遇到的问题，配置项看起来也没有问题，建议可以检查一下浏览器的代理网络配置

搞定了，大概率是油猴脚本的问题，连不上的是用油猴脚本的沉浸式翻译。
后来换了chrome的插件，就可以了。
谢谢作者。

**Comment by 1nihao8** [comment]
是不是需要换api接口呀https://api.chatanywhere.tech

**Comment by 1nihao8** [comment]
这个key每天都更新都会有额度吗
