### ISSUE TITLE
使用 AMA 客户端，选择GPT-4，使用时返回错误信息：Invalid content type 'application/json', Expected 'text/event-stream'.

### ISSUE THREAD

**Issue by qiqihaobenben** [chatanywhere/GPT_API_free#163]
**Describe the bug 描述bug**
使用 AMA 客户端，选择GPT-4，使用时返回错误信息：Invalid content type 'application/json', Expected 'text/event-stream'.

**To Reproduce 复现方法**
使用GPT-3没有问题，但是使用GPT-4就会报错

**Screenshots 截图**
![image](https://github.com/chatanywhere/GPT_API_free/assets/17338241/b11f5657-e9e7-49d2-bdc5-e7501d6efdf8)

**Tools or Programming Language 使用的工具或编程语言**
AMA

**Comment by chatanywhere** [comment]
免费的gpt-4不支持流传输 可能在某些软件中无法使用 我们未来会考虑做下兼容

**Comment by chatanywhere** [comment]
已经兼容了ama使用免费版gpt-4
