### ISSUE TITLE
403 limit to use gpt-3.5-turbo, gpt-4 and embeddings

### ISSUE THREAD

**Issue by PAYNEWATSON** [chatanywhere/GPT_API_free#164]
在使用FASTGPT时 报错，是做了屏蔽么？

**Comment by chatanywhere** [comment]
翻译一下报错 字面意思
<img width="859" alt="image" src="https://github.com/chatanywhere/GPT_API_free/assets/111742565/b5970ce6-41c6-48de-ab39-cc47e00bb0c7">
