### ISSUE TITLE
使用图像接口返回limit to use gpt-3.5-turbo, gpt-4 and embeddings

### ISSUE THREAD

**Issue by zybbq** [chatanywhere/GPT_API_free#165]
使用图像接口返回limit to use gpt-3.5-turbo, gpt-4 and embeddings

**Comment by zangqiourun** [comment]
俺也一样

**Comment by chatanywhere** [comment]
翻译一下报错 字面意思
<img width="859" alt="image" src="https://github.com/chatanywhere/GPT_API_free/assets/111742565/1de51faf-61cc-433a-b0b1-f0264ecd3c9b">

**Comment by lyl-eng** [comment]
解决了吗，我也遇到了

**Comment by chatanywhere** [comment]
免费key不支持，免费key使用图像接口肯定报错啊
