### ISSUE TITLE
请问每天免费的GPT4在哪申请，那个申请的内测是3.5的

### ISSUE THREAD

**Issue by RunPiBoss** [chatanywhere/GPT_API_free#166]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CellLz** [comment]
免费api就可以使用GPT4，只是每日有限额，如果跟你同一个IP的用户使用过了免费额度的话，那么你当日就用不了了。
