### ISSUE TITLE
代理最新的key失败

### ISSUE THREAD

**Issue by litongjava** [chatanywhere/GPT_API_free#169]
代理最新的key失败
我使用我从openai官方申请的key配合下面的代理 测试失败
转发Host1: https://api.chatanywhere.tech (国内中转，延时更低，host1和host2二选一)
转发Host2: https://api.chatanywhere.com.cn (国内中转，延时更低，host1和host2二选一)
转发Host3: https://api.chatanywhere.cn (国外使用,国内需要全局代理)

我使用我你提供 的api key配合上面的代理测试成功.这是为什么?

**Comment by ynpl** [comment]
转发只能用转发key, 你拿别人家钥匙开你家门能打开么

**Comment by shentong0722** [comment]
> 是不支持 从opneai官方申请的key吗?只能使用贵团队提供的key

是的，这是转发链接不是反代链接，你用官方的key自己用cf搭一个反代就行，四行代码的事儿

**Comment by litongjava** [comment]
请问cf的全称是什么

**Comment by chatanywhere** [comment]
cloudflare
