### ISSUE TITLE
接口返回：由于未使用流式响应导致超时，请务必使用流式响应以避免再次出现这种情况！如有疑问，请联系我们。

### ISSUE THREAD

**Issue by Chtholly1** [chatanywhere/GPT_API_free#17]
您好，我现在用的是免费api，麻烦问下上面的报错是什么情况？

另外，如果我用付费api的话是否就不会出现这种报错了？

**Comment by chatanywhere** [comment]
并不是的，字面意思，请使用流式响应，请求参数的加上`stream=true`，并接收服务器的SSE响应。具体请查找搜索引擎。
