### ISSUE TITLE
gpt-3.5-turbo模型，zotero为6.0.30版本。运行时出现如图提示，请问改如何操作？

### ISSUE THREAD

**Issue by Evan-diver** [chatanywhere/GPT_API_free#170]
![屏幕截图 2024-01-08 165943](https://github.com/chatanywhere/GPT_API_free/assets/77486914/2625e23d-9918-4048-95c3-5368e08d362e)
**Describe the bug 描述bug**

**To Reproduce 复现方法**

**Screenshots 截图**

**Tools or Programming Language 使用的工具或编程语言**
Describe in detail the GPT tool or programming language you used to encounter the problem

**Additional context 其他内容**

**Comment by ynpl** [comment]
换成.tech的那个接口试试

**Comment by chatanywhere** [comment]
你应该没有填Key或者key填错了吧
