### ISSUE TITLE
玩锤子，demo都报错

### ISSUE THREAD

**Issue by jqsl2012** [chatanywhere/GPT_API_free#173]
**Describe the bug 描述bug**

**To Reproduce 复现方法**

**Screenshots 截图**

**Tools or Programming Language 使用的工具或编程语言**
Describe in detail the GPT tool or programming language you used to encounter the problem

**Additional context 其他内容**

**Comment by chatanywhere** [comment]
demo已更新
另外，建议参考README的*常见软件插件使用方法*部分进行使用，如需编码使用，可以参考API文档https://chatanywhere.apifox.cn
