### ISSUE TITLE
The number of prompt tokens for free accounts is limited to 4000. If you have additional requirements, 

### ISSUE THREAD

**Issue by Fenhy** [chatanywhere/GPT_API_free#177]
![image](https://github.com/chatanywhere/GPT_API_free/assets/16318946/aa7b8621-1a62-4568-ae4f-25674a22d02d)
2024年01月17日 刚刚使用就报这个错， 换了一个 token 也是如此，看起来像是API 域名转发的频次限制。

**Comment by loukai99** [comment]
建议翻译一下，这里的意思是你的上下文最长是4000，你传的上下文太多了

**Comment by mimimidewo** [comment]
> 建议翻译一下，这里的意思是你的上下文最长是4000，你传的上下文太多了

测试过，不是上下文长度。 
![image](https://github.com/chatanywhere/GPT_API_free/assets/156872598/d9b99540-9d03-4846-8d10-49635efb40f2)

**Comment by Fenhy** [comment]
> 建议翻译一下，这里的意思是你的上下文最长是4000，你传的上下文太多了

不是上下文长度问题。
![image](https://github.com/chatanywhere/GPT_API_free/assets/16318946/54b2a595-0dda-44cd-be8e-e365db83d6c4)

**Comment by loukai99** [comment]
上下文是指当前对话所有的内容，不是你最近的一句话，你开个新对话试试

**Comment by Fenhy** [comment]
> 上下文是指当前对话所有的内容，不是你最近的一句话，你开个新对话试试

可以了，原来是这个限制，感谢解答！
