### ISSUE TITLE
vscode  codegpt插件使用

### ISSUE THREAD

**Issue by gumbp** [chatanywhere/GPT_API_free#178]
** 描述bug**
请问最新版的vscode codegpt插件如何使用该api？
我查询了该插件目录，并未找到hostname字段并可修改为api.chatanywhere.com.cn
在之前的codegpt版本中我是可以正常使用的。
**Screenshots 截图**
![image](https://github.com/chatanywhere/GPT_API_free/assets/57428207/9b50e96e-2ca2-4d22-b277-85c17bf10453)

**Tools or Programming Language 使用的工具或编程语言**
win10 os

**Comment by ynpl** [comment]
这个插件得新版好像不支持修改url

**Comment by gumbp** [comment]
那只能是回退到旧版本咯
