### ISSUE TITLE
403 - Limit to use gpt-3.5-turbo, gpt-4 and embeddings. 

### ISSUE THREAD

**Issue by nanabenren** [chatanywhere/GPT_API_free#179]
Suddenly, the free key cannot be used properly.What happened when the following message appeared？
403 - Limit to use gpt-3.5-turbo, gpt-4 and embeddings. If you have additional requirements, please visit https://peiqishop.me to purchase a premium key.

**Comment by 2632471948** [comment]
你解决了吗 我也遇到了这个问题

**Comment by texaspandaa** [comment]
same here
