### ISSUE TITLE
购买的API-KEY不能在zotero里使用

### ISSUE THREAD

**Issue by Nicolehuangc** [chatanywhere/GPT_API_free#181]
按照说明文字在zotero里设置好了API-key
![IMG_6456](https://github.com/chatanywhere/GPT_API_free/assets/39021750/0052d128-2702-4ae4-b60b-a2a4d1a81882)
但是使用的时候报错，说该API-key不存在
![IMG_6457](https://github.com/chatanywhere/GPT_API_free/assets/39021750/6ef94996-6f88-4cbc-9fb5-1b28f1755ee2)

**Comment by chatanywhere** [comment]
未配置接入url
仔细阅读readme按要求配置不要漏步骤
