### ISSUE TITLE
可以使用免费gpt key实现assistant的创建和使用吗

### ISSUE THREAD

**Issue by qunchaozhou** [chatanywhere/GPT_API_free#184]
**Describe the bug 描述bug**

**To Reproduce 复现方法**

**Screenshots 截图**

**Tools or Programming Language 使用的工具或编程语言**
Describe in detail the GPT tool or programming language you used to encounter the problem

**Additional context 其他内容**

**Comment by ynpl** [comment]
不能

**Comment by chatanywhere** [comment]
支持模型可以参考 https://chatanywhere.apifox.cn/doc-2694962 的模型列表发自我的 iPhone在 2024年1月30日，17:37，qunchaozhou ***@***.***> 写道：﻿
付费版是除了官方的哪些服务或者版本不能用?还是目前都支持了?
