### ISSUE TITLE
zotero 中GPT用不了

### ISSUE THREAD

**Issue by LongYistar** [chatanywhere/GPT_API_free#185]
有时候显示timed out 
有时候显示400 BAD REQUEST

**Comment by LongYistar** [comment]
![微信图片_20240131150028](https://github.com/chatanywhere/GPT_API_free/assets/66472941/5afd3ce3-4316-4c60-bffc-0039817b5f9c)

**Comment by chatanywhere** [comment]
该问题是由于zotero gpt插件的问题导致，因为接口input数组的大小不能超过2048，超过后就会报错这个，要解决这个问题你只能去zotero gpt的github咨询作者，或者拆封缩短你文档的大小。

**Comment by xp-one** [comment]
前面就是可以，现状不知道怎么抽风了

**Comment by STJKWSRJ** [comment]
> 有时候显示timed out 有时候显示400 BAD REQUEST

我也是 zotero中gpt用不了 超时

**Comment by Hailong-Chang** [comment]
![zotero](https://github.com/chatanywhere/GPT_API_free/assets/138642889/0f5c4929-4073-459f-bb75-71de59c93d1f)
请问这种情况是什么问题呢

**Comment by Amanciee** [comment]
请问解决了吗

**Comment by xp-one** [comment]
解决了，代理问题。换节点。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月02日 20:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [chatanywhere/GPT_API_free] zotero 中GPT用不了 (Issue #185) |

请问解决了吗
