### ISSUE TITLE
免费key用不了

### ISSUE THREAD

**Issue by chatGPT-AI-API** [chatanywhere/GPT_API_free#186]
提示：OpenAI 密钥不正确。请确保您的 OpenAI API 密钥正确无误，或在您的 OpenAI 仪表板上创建新的 OpenAI API 密钥。或者，您可以直接在此网站上购买代码生成积分。

**Comment by ynpl** [comment]
你改api地址了么

**Comment by LeungJun24** [comment]
报错同一楼，同样使用不了

**Comment by chatanywhere** [comment]
仔细阅读readme，使用前要修改接入点url

**Comment by chatGPT-AI-API** [comment]
（看图）改的位置都没有，根本改不了
(Look at the picture) There's no place to change it, you can't change it at all.
![捕获](https://github.com/chatanywhere/GPT_API_free/assets/130991061/7d710bfd-d278-40d2-9fee-2ef29877dca6)

**Comment by ynpl** [comment]
> （看图）改的位置都没有，根本改不了 (Look at the picture) There's no place to change it, you can't change it at all. ![捕获](https://private-user-images.githubusercontent.com/130991061/304336703-7d710bfd-d278-40d2-9fee-2ef29877dca6.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTQ3NzIsIm5iZiI6MTcwNzgxNDQ3MiwicGF0aCI6Ii8xMzA5OTEwNjEvMzA0MzM2NzAzLTdkNzEwYmZkLWQyNzgtNDBkMi05ZmVlLTJlZjI5ODc3ZGNhNi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QwODU0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzU4YTExODA5NjFiOTBmODRiNGMxMTI0ZmI5NDI2Njg5NzQyMmQ1N2ZhMjQyM2E4ZWQwYzRhZGYxNmJkYTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NAxI3Ut66P6_H8Fx62ppkJKWJ8htjJT1_9_seAGGIZw)

那说明你用的不支持更改api地址, 联系你用的项目的开发者

**Comment by bailitingqin** [comment]
我也遇到了不能用的场景，不过提示的是要求recharge。。。

Your account balance is insufficient.
免费的也要recharge么？
虽然我也有付费的，但是平时还是用免费的那个。

**Comment by ynpl** [comment]
> 我也遇到了不能用的场景，不过提示的是要求recharge。。。
> 
> Your account balance is insufficient. 免费的也要recharge么？ 虽然我也有付费的，但是平时还是用免费的那个。

余额不足只会出现在付费的key上

**Comment by bailitingqin** [comment]
难道是我用混了……o(╥﹏╥)o

**Comment by bailitingqin** [comment]
换了一个，现在提示是Limi to use gpt-3.5-turb,gpt-4 and embeddings.

**Comment by ynpl** [comment]
> 换了一个，现在提示是Limi to use gpt-3.5-turb,gpt-4 and embeddings.
免费的不能用免费以外的模型, 你用了不是免费的模型了

**Comment by bailitingqin** [comment]
我选的是gpt-3.5-turb,也不行么？那应该选哪个呀？我用的是chat box

**Comment by ynpl** [comment]
> 我选的是gpt-3.5-turb,也不行么？那应该选哪个呀？我用的是chat box

检查一下自己得用法 报错不会骗人的

**Comment by bailitingqin** [comment]
我试了3.5的不同版本，好像是16k-0613不行了，只选3.5-turb是可以的

**Comment by ynpl** [comment]
是的哦 文档里面写了的 免费不支持16k

**Comment by bailitingqin** [comment]
好的，谢谢，原来我一直用的是收费版本
