### ISSUE TITLE
收费标准似乎不正确？

### ISSUE THREAD

**Issue by bailitingqin** [chatanywhere/GPT_API_free#189]
以下是我尝试的两次问答及收费情况。
![Screenshot from 2024-02-23 09-26-00](https://github.com/chatanywhere/GPT_API_free/assets/136884855/cb998e48-6f9c-401e-93f9-2efe204fb356)

明显不是收费中提到的0.07/1k tokens.
![Screenshot from 2024-02-23 09-26-09](https://github.com/chatanywhere/GPT_API_free/assets/136884855/fe9c93ea-8572-4630-9058-71dd53c4f635)

所以到底是哪里出问题了呢？

**Comment by chatanywhere** [comment]
completion token(回答的token)是0.21啊
<img width="524" alt="image" src="https://github.com/chatanywhere/GPT_API_free/assets/111742565/c296993a-4b3f-4bad-94c3-c5daf2a2192c">

**Comment by bailitingqin** [comment]
啊！我页面比较窄，没看到后面。现在看到了。
