### ISSUE TITLE
新版ChatGPT-Next-Web 无法使用

### ISSUE THREAD

**Issue by loveshens** [chatanywhere/GPT_API_free#19]
![image](https://github.com/chatanywhere/GPT_API_free/assets/65337490/c24fbe46-ef51-4fd7-be31-267fbdc93bf4)
购买了付费的

**Comment by chatanywhere** [comment]
请明确你的配置参数，配置方法，遇到的具体问题等，你这样提问我无法帮你定位问题，或者加QQ群提问也可以。
