### ISSUE TITLE
是否支持assistant api

### ISSUE THREAD

**Issue by Hanzhang-lang** [chatanywhere/GPT_API_free#190]
**调用官方assistants相关代码显示not found**

**复现方法**
assistant = client.beta.assistants.create(
    ...:     name="Math Tutor",
    ...:     instructions="You are a personal math tutor. Write and run code to answer math questions.",
    ...:     tools=[{"type": "code_interpreter"}],
    ...: 
    ...:     model="gpt-4-turbo-preview"
    ...: )

**截图**
![image](https://github.com/chatanywhere/GPT_API_free/assets/66400564/69a87d32-64ce-444d-9890-e971cb07055f)

**Comment by ynpl** [comment]
不支持
