### ISSUE TITLE
如何接入Unity

### ISSUE THREAD

**Issue by noiz321** [chatanywhere/GPT_API_free#192]
我之前按照一个github的教程的方法是在c盘建立一个JSON文件
里面的格式是这样
{
  "api_key": "xxxx",
  "organization": "xxxxx"
}

想请问这个api是能接入到unity吗？谢谢

教程
https://github.com/srcnalt/OpenAI-Unity.git

**Comment by ynpl** [comment]
应该不能的, 你得问问那项目的开发者能不能支持第三方的api

**Comment by notedwin-dev** [comment]
> 我之前按照一个github的教程的方法是在c盘建立一个JSON文件 里面的格式是这样 { "api_key": "xxxx", "organization": "xxxxx" }
> 
> 想请问这个api是能接入到unity吗？谢谢
> 
> 教程 https://github.com/srcnalt/OpenAI-Unity.git

可以的，只需要在[这个file里面](https://github.com/srcnalt/OpenAI-Unity/blob/master/Runtime/OpenAIApi.cs)更改API的接口网址就行可以了。看README里面的教程。有详细说到要把所有OpenAI借口网址改成什么。
