### ISSUE TITLE
Zotero—GPT显示请求太多，要不就是网络错误，求大神！！！！

### ISSUE THREAD

**Issue by 2000Laiyancheng** [chatanywhere/GPT_API_free#196]
![image](https://github.com/chatanywhere/GPT_API_free/assets/152827888/68c56f6c-3581-4f51-850b-169a46bb0cad)
![image](https://github.com/chatanywhere/GPT_API_free/assets/152827888/57b81dac-feba-4e62-9690-1ce23e87411a)

Zotero-GPTAPI和秘钥都配置好了但是不能用，求大神帮助！

**Comment by ynpl** [comment]
免费的一小时60次 你这超过次数了

**Comment by chatanywhere** [comment]
api.chatanywhere.cn域名是境外专用，境内不稳定。
显示请求太多就是你用的ip或者你的key超过每小时60次了，readme都有具体说明，请仔细阅读
