### ISSUE TITLE
403 FORBIDDEN "The number of prompt tokens for free accounts is limited to 4096." 问题出现的原因

### ISSUE THREAD

**Issue by MangoTY** [chatanywhere/GPT_API_free#198]
![微信截图_20240320102702](https://github.com/chatanywhere/GPT_API_free/assets/140579539/8b41a36c-98df-4462-9892-77be05037a1a)

**Comment by Junjie-Jin** [comment]
刚刚申请，也是这个问题。请问解决了吗？

**Comment by ynpl** [comment]
免费key 最多4096 你这个太长了

**Comment by chatanywhere** [comment]
免费key限制了输入token（提问的问题总长度）最大为4096，你可以减少输入或者购买付费key并使用gpt-3.5-turbo-0125模型。
PS：你可能好奇明明你的问题很简短，不可能有4000字，但实际上这是zotero-gpt的原理导致的，它将你的文章拆分成小段落，然后根据你提出的问题匹配相关的段落，将原文段落和你的问题一起传给gpt让gpt做出回答，这种模式注定了你的输入问题总字数很容易超过4096。

**Comment by lujiashun1** [comment]
我的也是 但是我就输入了几个字

**Comment by bit-wayti** [comment]
没有需要的话，可以把“上下文的消息数量上限”调一调，我是这么搞的，有点用

**Comment by ynpl** [comment]
> 我的也是 但是我就输入了几个字

上下文, 不是你单次输入 你清空上下文就好了

**Comment by youfeilong** [comment]
我好像清空也没有用，只能调成3.5才有用

**Comment by cymbg** [comment]
解决了，把上下文改成10

**Comment by wengzhenquan** [comment]
> 解决了，把上下文改成10

什么上下文？是哪个参数吗？

**Comment by cymbg** [comment]
> > 解决了，把上下文改成10
> 
> 什么上下文？是哪个参数吗？

上下文的消息数量上限，在设置里面

**Comment by wengzhenquan** [comment]
> > > 解决了，把上下文改成10
> > 
> > 
> > 什么上下文？是哪个参数吗？
> 
> 上下文的消息数量上限，在设置里面

是max_tokens参数吗？
我调了，没效果。
是不是我找错了？

**Comment by SummersSigh** [comment]
为什么直接问他问题能够回答，但是一按AskPDF（Full text）就会有这个报错呢

**Comment by Rose-daiyishu** [comment]
> 解决了，把上下文改成10

谢谢，我也解决了
