### ISSUE TITLE
error code 401

### ISSUE THREAD

**Issue by SeanXin69** [chatanywhere/GPT_API_free#199]
刚申请的，不存在泄露，免费的是现在用不了吗？
AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-NjJvl***************************************gtyk. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

**Comment by SeanXin69** [comment]
已解决，chatanywhere的问题

**Comment by SuccuFy** [comment]
打扰一下，可以问一下如何配置host吗？
