### ISSUE TITLE
免费API key用langchain.embeddings的时候出错

### ISSUE THREAD

**Issue by gsoec** [chatanywhere/GPT_API_free#2]
```
Retrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 10.0 seconds as it raised APIError: HTTP code 500 from API (Request method 'POST' not supported).
```
请问一下免费key是不支持embeddings吗？

**Comment by chatanywhere** [comment]
检查了一下是因为不兼容langchain导致的，可以按照以下图片中的方式修改一下langchain临时解决。后续有空再处理兼容性问题。
![@P 7)AD%~%_9}7QKQCN~D9](https://github.com/chatanywhere/GPT_API_free/assets/111742565/015e3fab-3ce4-47ce-b2ac-5cb92cd04906)
