### ISSUE TITLE
付费API key报错429错误

### ISSUE THREAD

**Issue by Sanguine-00** [chatanywhere/GPT_API_free#200]
**Describe the bug 描述bug**
付费API key报错429错误

**To Reproduce 复现方法**
发了一条信息之后, 接着询问时出现的. 之前没有遇到过这样的问题
**Screenshots 截图**
![image](https://github.com/chatanywhere/GPT_API_free/assets/18140259/5f78e23e-d43f-4dc6-9b78-b09760a16ef7)

**Tools or Programming Language 使用的工具或编程语言**
Botgem

**Additional context 其他内容**

**Comment by chatanywhere** [comment]
gpt-4-v受到官方的调用限制，可以等一会儿再试
