### ISSUE TITLE
academic gpt - limited to use gpt-3.5-turbo, 403 forbidden 

### ISSUE THREAD

**Issue by texaspandaa** [chatanywhere/GPT_API_free#201]
感谢作者的分享。 求助一下，我在配置完academic gpt后 （国内使用，没用代理），配置如下

API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://api.chatanywhere.tech/v1/chat/completions"}
api key用的是免费内测版，打开academic gpt后报错如下
![gpterrorScreenshot 2024-03-25 222534](https://github.com/chatanywhere/GPT_API_free/assets/12231539/87c05b10-6126-497c-bcc1-b07fa14aaf8c)

麻烦帮忙看一下，感谢！

**Comment by chatanywhere** [comment]
报错里应该说的挺明确了，你使用了gpt-3.5-turbo-16k模型，但免费key是不支持这个模型的

**Comment by tayton42** [comment]
> 报错里应该说的挺明确了，你使用了gpt-3.5-turbo-16k模型，但免费key是不支持这个模型的

你好，我使用的3.5turbo模型，之前是正常的，今天提示这个
[Local Message] 异常

```
Traceback (most recent call last):
  File ".\request_llms\bridge_chatgpt.py", line 223, in predict
    chunk = next(stream_response)
StopIteration
```
{"error":{"message":"too many requests","type":"chatanywhere_error","param":null,"code":"429 TOO_MANY_REQUESTS"}}
是请求太多造成的吗，但我已经更换了其他的免费api，还是会报一样的错误
