### ISSUE TITLE
免费key，等了三个小时再使用报了429的错误

### ISSUE THREAD

**Issue by aloha66** [chatanywhere/GPT_API_free#203]
早上因为操作不当，多调了几次接口，报了429之后，现在过了几个小时还是报429。刚刚查一下已用额度0.28.应该怎么解决呢？

**Comment by ynpl** [comment]
免费API Key限制150请求/24小时/IP&Key调用频率，也就是说你如果在一个IP下使用多个Key，所有Key的每24小时请求数总和不能超过150；同理，你如果将一个Key用于多个IP，这个Key的每24小时请求数也不能超过150。(付费版API没有这个限制)
