### ISSUE TITLE
如何用官方密钥接入api接口

### ISSUE THREAD

**Issue by xiba191729** [chatanywhere/GPT_API_free#204]
作者您好，非常感谢您提供了这个渠道！
我想问一下为什么我用gpt官方的api key没法接入您的接口呢？报错如下

Error: HTTP POST https://api.chatanywhere.tech/v1/chat/completions failed with status code 401:

{"error":{"message":"wrong api key","type":"chatanywhere_error","param":null,"code":"401 UNAUTHORIZED"}}
这是不是说明官方api key没被授权无法使用该接口啊
另外就是免费版api key是要定时重新申请吗，我也想咨询一下，谢谢！

**Comment by ynpl** [comment]
1转发key只能用转发api接口 2不用

**Comment by xiba191729** [comment]
好的，感谢作者！
其实我原本是想用我自己的GPT key去接入您的转发api的，然后才意识到应该是我账户里没余额导致无法调用key才报错（后面报了个429的错误，显示unsuffient token）
再次感谢作者的付出！！

**Comment by pizhongpi** [comment]
我也出现了这个报错，请问后续是怎么解决的

**Comment by xiba191729** [comment]
> 我也出现了这个报错，请问后续是怎么解决的

我是发现用自己的api key无法调度，调度要钱，我账户里没余额。然后密钥用了作者的免费密钥就行了。不过每天只能调度150次

**Comment by pizhongpi** [comment]
您是使用的gpt学术版吗？可以加个微信交流一下嘛

**Comment by chatanywhere** [comment]
关于我们的密钥和OpenAI官方密钥混用的问题
1. 如果你使用我们的接口，是无法使用OpenAI官方获取的密钥的，一般来说会遇到楼主遇到的报错 401 {"error":{"message":"wrong api key","type":"chatanywhere_error","param":null,"code":"401 UNAUTHORIZED"}}，你必须使用申请的免费密钥才可以正常访问。
2. 如果你使用我们的密钥，同理是无法访问OpenAI官方的接口，一般会报错 401 {'error': {'message': 'Incorrect API key provided: sk-NjJvl***************************************gtyk. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}，这时你必须将接口，也就是README教程中让你修改的URL换成我们的接入点url。

**Comment by cenking12** [comment]
你好 请问如果使用官方密钥的话是不是找不到对应的接口呀

**Comment by YiInin** [comment]
zotero的gpt总是报错，这个问题怎么解决哇？
【出错了，下面是一些报错信息：
HTTP POST https://api.chatanywhere.tech/v1/chat/completions failed with status code 403:
{“error”:{“message”:“免费API限制模型输入token小于4096，如有更多需求，请访问 https://buyca.tech 购买付费API。The number of prompt tokens for free accounts is limited to 4096. If you have additional requirements, please visit https://buyca.tech to purchase a premium key.”,“type”:“chatanywhere_error”,“param”:null,“code”:“403 FORBIDDEN”}}
如果是网络问题，建议优化网络，比如打开/切换代理等。
full api https://api.chatanywhere.tech/v1/chat/completions
secretKey sk-…HmZP
model gpt-3.5-turbo
temperature 0.3】

**Comment by ynpl** [comment]
> zotero的gpt总是报错，这个问题怎么解决哇？ 【出错了，下面是一些报错信息： HTTP POST https://api.chatanywhere.tech/v1/chat/completions failed with status code 403: {“error”:{“message”:“免费API限制模型输入token小于4096，如有更多需求，请访问 https://buyca.tech 购买付费API。The number of prompt tokens for free accounts is limited to 4096. If you have additional requirements, please visit https://buyca.tech to purchase a premium key.”,“type”:“chatanywhere_error”,“param”:null,“code”:“403 FORBIDDEN”}} 如果是网络问题，建议优化网络，比如打开/切换代理等。 full api https://api.chatanywhere.tech/v1/chat/completions secretKey sk-…HmZP model gpt-3.5-turbo temperature 0.3】

这个报错已经显示的很明白啦 ....  你得字太多了 免费的最多单词请求4096token 你得文章太长了
