### ISSUE TITLE
demo.py报错

### ISSUE THREAD

**Issue by LikeFlyingPanda** [chatanywhere/GPT_API_free#205]
**Describe the bug 描述bug**
发生异常: TypeError
ConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
  File "chatgpt-api.py", line 8, in <module>
    client = OpenAI(
TypeError: ConnectionPool.__init__() got an unexpected keyword argument 'socket_options'

**Tools or Programming Language 使用的工具或编程语言**
python
vscode

**Comment by ynpl** [comment]
TypeError: ConnectionPool.init() got an unexpected keyword argument 'socket_options'

 检查下自己代码

**Comment by chatanywhere** [comment]
应该是你的网络原因导致
