### ISSUE TITLE
ZoteroGPT插件突然无法使用

### ISSUE THREAD

**Issue by ComradePenguin-1917** [chatanywhere/GPT_API_free#207]
**Describe the bug 描述bug**
在Zotero内安装GPT插件，使用chatanywhere API接口时，出现报错，同时使用沉浸式翻译正常。

错误提示：
出错了，下面是一些报错信息：
HTTP POST https://api.chatanywhere.tech/v1/chat/completions failed with status code 400:{“error”:{“message”:“Invalid value for ‘content’: expected a string, got null.”,“type”:“invalid_request_error”,“param”:“messages.[2].content”,“code”:null}}
如果是网络问题，建议优化网络，比如打开/切换代理等。

**Comment by ynpl** [comment]
这种建议您询问Zotero-GPT的开发着, 这非转发的问题
