### ISSUE TITLE
An error occurred while testing GPT API connection: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by good-good-studyy** [chatanywhere/GPT_API_free#208]
在JupyterNotebook运行如下代码：
import openai

# 设置您的 API 密钥
api_key = "sk-"
openai.api_key = api_key
openai.api_base = "https://api.chatanywhere.tech"

# 测试连接
try:
    response = openai.Completion.create(
      engine="text-davinci-002",
      prompt="Once upon a time",
      max_tokens=50
    )
    print(response.data)
except Exception as e:
    print(f"An error occurred while testing GPT API connection: {e}")
提示错误：
An error occurred while testing GPT API connection: 'str' object has no attribute 'get'
怎么解决？

**Comment by chatanywhere** [comment]
首先，建议将openai包升级到最新的版本后参考readme配置正确的base_url使用
另外，据我所知text-davinci-002模型已经被openai弃用，现在可以使用的基础补全模型应该是davinci-002

**Comment by good-good-studyy** [comment]
请问正确的base_url是哪一个？只要将openai_base＝这个url就行吗？





---Original---
From: ***@***.***&gt;
Date: Sat, Apr 6, 2024 18:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chatanywhere/GPT_API_free] An error occurred while testing GPTAPI connection: 'str' object has no attribute 'get' (Issue #208)




 
首先，建议将openai包升级到最新的版本后参考readme配置正确的base_url使用
 另外，据我所知text-davinci-002模型已经被openai弃用，现在可以使用的基础补全模型应该是davinci-002

**Comment by chatanywhere** [comment]
参考readme或者dome.py

**Comment by good-good-studyy** [comment]
升级了openai，并设置好了API base和API key，且模型换成了davinci-002，但还是显示相同的错误，请问怎么解决呢？



---Original---
From: ***@***.***&gt;
Date: Sat, Apr 6, 2024 18:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chatanywhere/GPT_API_free] An error occurred while testing GPTAPI connection: 'str' object has no attribute 'get' (Issue #208)




 
参考readme或者demo.py

**Comment by chatanywhere** [comment]
提供源码和日志

**Comment by good-good-studyy** [comment]
2024-04-07 16:46:17,857 - root - INFO - 尝试连接到OpenAI API 2024-04-07 16:46:17,858 - openai - DEBUG - message='Request to OpenAI API' method=post path=https://api.chatanywhere.cn/v1/engines/davinci-002/completions 2024-04-07 16:46:17,859 - openai - DEBUG - api_version=None data='{"prompt": "Once upon a time", "max_tokens": 50}' message='Post details' 2024-04-07 16:46:17,861 - urllib3.util.retry - DEBUG - Converted retries value: 2 -&gt; Retry(total=2, connect=None, read=None, redirect=None, status=None) 2024-04-07 16:46:17,866 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.chatanywhere.cn:443 2024-04-07 16:46:38,909 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/v1/engines/davinci-002/completions'): Retry(total=1, connect=None, read=None, redirect=None, status=None) 2024-04-07 16:46:38,911 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024E2C646A00&gt;: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。')': /v1/engines/davinci-002/completions 2024-04-07 16:46:38,914 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): api.chatanywhere.cn:443 2024-04-07 16:46:59,958 - urllib3.util.retry - DEBUG - Incremented Retry for (url='/v1/engines/davinci-002/completions'): Retry(total=0, connect=None, read=None, redirect=None, status=None) 2024-04-07 16:46:59,961 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024E4C139C10&gt;: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。')': /v1/engines/davinci-002/completions 2024-04-07 16:46:59,962 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (3): api.chatanywhere.cn:443 2024-04-07 16:47:21,013 - root - ERROR - 在测试GPT API连接时发生错误: Error communicating with OpenAI: HTTPSConnectionPool(host='api.chatanywhere.cn', port=443): Max retries exceeded with url: /v1/engines/davinci-002/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024E4C139970&gt;: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。')) 




卡布奇诺
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatanywhere/GPT_API_free"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月7日(星期天) 下午4:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatanywhere/GPT_API_free] An error occurred while testing GPT API connection: 'str' object has no attribute 'get' (Issue #208)





 
提供源码和日志

**Comment by chatanywhere** [comment]
![image](https://github.com/chatanywhere/GPT_API_free/assets/111742565/6ca5bab0-6d19-428f-8999-b25e08eab072)

**Comment by good-good-studyy** [comment]
改成host1或host2还是连接不上







卡布奇诺
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "chatanywhere/GPT_API_free"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月7日(星期天) 下午4:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatanywhere/GPT_API_free] An error occurred while testing GPT API connection: 'str' object has no attribute 'get' (Issue #208)





 
image.png (view on web)

**Comment by chatanywhere** [comment]
```python
from openai import OpenAI
client = OpenAI(
    api_key="YOUR API KEY",
    base_url="https://api.chatanywhere.tech/v1"
)
completion = client.completions.create(model="davinci-002", prompt="say hello", max_tokens=50)
print(completion.choices[0].text)
```

似乎你的源码还存在其他问题，你可以参考以上源码。你所遇到的问题，都可以在[openai官方文档](https://platform.openai.com/docs/guides/text-generation/completions-api)以及README中找到解决方法，如果你想要更进一步使用openai包进行编程，建议你仔细阅读[openai官方文档](https://platform.openai.com/docs/guides/text-generation/completions-api)以及本项目README后继续。

**Comment by good-good-studyy** [comment]
提供的代码在JupyterNotebook上运行不了：



卡布奇诺
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatanywhere/GPT_API_free"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月7日(星期天) 下午5:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatanywhere/GPT_API_free] An error occurred while testing GPT API connection: 'str' object has no attribute 'get' (Issue #208)





 from openai import OpenAI client = OpenAI(     api_key="YOUR API KEY",     base_url="https://api.chatanywhere.tech/v1" ) completion = client.completions.create(model="davinci-002", prompt="say hello", max_tokens=50) print(completion.choices[0].text)
 
似乎你的源码还存在其他问题，你可以参考以上源码。你所遇到的问题，都可以在openai官方文档以及README中找到解决方法，如果你想要更进一步使用openai包进行编程，建议你仔细阅读openai官方文档以及本项目README后继续。

**Comment by chatanywhere** [comment]
提供错误截图

**Comment by good-good-studyy** [comment]
&nbsp;



卡布奇诺
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatanywhere/GPT_API_free"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月7日(星期天) 下午5:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatanywhere/GPT_API_free] An error occurred while testing GPT API connection: 'str' object has no attribute 'get' (Issue #208)





 
提供错误截图

**Comment by good-good-studyy** [comment]
升级openai后报错：
--------------------------------------------------------------------------- PermissionDeniedError                     Traceback (most recent call last) ~\AppData\Local\Temp/ipykernel_4936/1082049149.py in <module&gt;       4     base_url="https://api.chatanywhere.tech/v1"       5 ) ----&gt; 6 completion = client.completions.create(model="davinci-002", prompt="say hello", max_tokens=50)       7 print(completion.choices[0].text) ~\AppData\Roaming\Python\Python39\site-packages\openai\_utils\_utils.py in wrapper(*args, **kwargs)     273                         msg = f"Missing required argument: {quote(missing[0])}"     274                 raise TypeError(msg) --&gt; 275             return func(*args, **kwargs)     276      277         return wrapper  # type: ignore ~\AppData\Roaming\Python\Python39\site-packages\openai\resources\completions.py in create(self, model, prompt, best_of, echo, frequency_penalty, logit_bias, logprobs, max_tokens, n, presence_penalty, seed, stop, stream, suffix, temperature, top_p, user, extra_headers, extra_query, extra_body, timeout)     514         timeout: float | httpx.Timeout | None | NotGiven = NOT_GIVEN,     515     ) -&gt; Completion | Stream[Completion]: --&gt; 516         return self._post(     517             "/completions",     518             body=maybe_transform( ~\AppData\Roaming\Python\Python39\site-packages\openai\_base_client.py in post(self, path, cast_to, body, options, files, stream, stream_cls)    1211             method="post", url=path, json_data=body, files=to_httpx_files(files), **options    1212         ) -&gt; 1213         return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))    1214     1215     def patch( ~\AppData\Roaming\Python\Python39\site-packages\openai\_base_client.py in request(self, cast_to, options, remaining_retries, stream, stream_cls)     900         stream_cls: type[_StreamT] | None = None,     901     ) -&gt; ResponseT | _StreamT: --&gt; 902         return self._request(     903             cast_to=cast_to,     904             options=options, ~\AppData\Roaming\Python\Python39\site-packages\openai\_base_client.py in _request(self, cast_to, options, remaining_retries, stream, stream_cls)     991      992             log.debug("Re-raising status error") --&gt; 993             raise self._make_status_error_from_response(err.response) from None     994      995         return self._process_response( PermissionDeniedError: Error code: 403 - {'error': {'message': '免费API限制使用gpt-3.5-turbo，gpt-4 和 embeddings模型，如有更多需求，请访问 https://buyca.top 购买付费API。The free account is limited to use gpt-3.5-turbo, gpt-4 and embeddings. If you have additional requirements, please visit https://buyca.top to purchase a premium key.', 'type': 'chatanywhere_error', 'param': None, 'code': '403 FORBIDDEN'}} 



卡布奇诺
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatanywhere/GPT_API_free"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月7日(星期天) 下午5:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatanywhere/GPT_API_free] An error occurred while testing GPT API connection: 'str' object has no attribute 'get' (Issue #208)





 
提供错误截图

**Comment by chatanywhere** [comment]
![image](https://github.com/chatanywhere/GPT_API_free/assets/111742565/c3156369-4f60-4636-a07e-8db4946d4ce2)
这报错，中文应该不难看懂吧

**Comment by good-good-studyy** [comment]
我只需要用GPT3.5以下就够了，你回复的用来测试的代码怎要用到付费的呢？？



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 7, 2024 19:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chatanywhere/GPT_API_free] An error occurred while testing GPTAPI connection: 'str' object has no attribute 'get' (Issue #208)




 
image.png (view on web)
 这报错，中文应该不难看懂吧

**Comment by good-good-studyy** [comment]
你得给我一个能用来测试连接免费API的测试代码。。。还是说你们提供的全都是付费服务？



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 7, 2024 19:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chatanywhere/GPT_API_free] An error occurred while testing GPTAPI connection: 'str' object has no attribute 'get' (Issue #208)




 
image.png (view on web)
 这报错，中文应该不难看懂吧

**Comment by chatanywhere** [comment]
从一开始你就在提问completion模型为什么报错，我以为是项目的README以及demo只提供了chat模型（gpt）的使用方法，而没有提供completion模型的相关参考，导致你在使用completion模型时遇到了麻烦。因此，我按照你的需求提供了参考代码，我并不知道你是付费用户还是免费用户。而你所需要的_“你得给我一个能用来测试连接免费API的测试代码“_，项目中的[demo.py](https://github.com/chatanywhere/GPT_API_free/blob/main/demo.py)文件已经提供并附有相对完整的注释。
个人认为，非疑难问题，仔细阅读一遍README或许比在issues中提问更加节省时间。
![image](https://github.com/chatanywhere/GPT_API_free/assets/111742565/8095572a-3e41-4244-a118-56a43e249746)

**Comment by good-good-studyy** [comment]
1. 我仔细阅读了很多遍你们提供的README，试过了里面提供的所有的api_base的url，都出现一样的问题
'str' object has no attribute 'get' ，不管什么版本的openai都连接不上
2. 除了找你们API团队询问，我还查阅和使用了很多其他方法和网站，目前都还未解决这个问题，因为是你们团队提供的API key，找你们询问是很正常而且最容易解决一些这个api key特有的问题
3. 作为API团队回答问题的服务人员，你这态度确实比较差。不知道你们回答问题是个公益服务还是怎么的？？自己在网站上写的可以提问，用户提问了又来批评/贬低提问的用户。我用你们的服务，询问服务的具体细节，请问有何问题？
4. 我提出的问题很简单且基本，就我使用你们提供的key根本连接不上openai的API，目前我觉得问题可能和apibase和apikey的设置有关，需要你们团队提供原因和解决方案。你从头到尾回答就特别浅显，解决不了问题，而且逻辑混乱，根本不看清我的问题是什么，无语

---Original---
From: ***@***.***&gt;
Date: Sun, Apr 7, 2024 20:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chatanywhere/GPT_API_free] An error occurred while testing GPTAPI connection: 'str' object has no attribute 'get' (Issue #208)




 
从一开始你就在提问completion模型为什么报错，我以为是项目的README以及demo只提供了chat模型（gpt）的使用方法，而没有提供completion模型的相关参考，导致你在使用completion模型时遇到了麻烦。因此，我按照你的需求提供了参考代码，我并不知道你是付费用户还是免费用户。而你所需要的_“你得给我一个能用来测试连接免费API的测试代码“_，项目中的demo.py文件已经提供并附有相对完整的注释。
 个人认为，非疑难问题，仔细阅读一遍README或许比在issues中提问更加节省时间。
 image.png (view on web)

**Comment by good-good-studyy** [comment]
我之前发给你的那个代码是一个测试open aiAPI连接的代码，这个测试代码显示openai.completion.creat函数有点问题，然后在运行我原本要使用这个openAI key的代码时，completion函数再次出现了问题。并且如上一邮件所说试了所有url还是报错。在另一个显示日志的测试连接的代码当中，显示的是没办法连接上你们给的这个base的网站，错误码404。这就说明 在API连接时就出了问题，连接的问题是key和base的问题吗？还是其他原因？如果你觉得这个问题很简单很好解决，麻烦给出具体的解决方案



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 7, 2024 20:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chatanywhere/GPT_API_free] An error occurred while testing GPTAPI connection: 'str' object has no attribute 'get' (Issue #208)




 
从一开始你就在提问completion模型为什么报错，我以为是项目的README以及demo只提供了chat模型（gpt）的使用方法，而没有提供completion模型的相关参考，导致你在使用completion模型时遇到了麻烦。因此，我按照你的需求提供了参考代码，我并不知道你是付费用户还是免费用户。而你所需要的_“你得给我一个能用来测试连接免费API的测试代码“_，项目中的demo.py文件已经提供并附有相对完整的注释。
 个人认为，非疑难问题，仔细阅读一遍README或许比在issues中提问更加节省时间。
 image.png (view on web)

**Comment by chatanywhere** [comment]
最起码我觉得你既然选择了编写代码使用API，最起码也是个技术人员，应该知道每次提问应该附带上自己的源码和完整的报错信息，而从头到尾，你只提供了一次源码，后续甚至连报错都要我不断重复让你提供，我根本无法从你的提问中发现你的问题所在，我只能找到你第一次提供的源码所存在的问题，而后面，你把自己的代码修改成了什么样子，我根本无从知晓。

而你说的，你怀疑是什么什么问题，我觉得最好的排查方法是直接将demo的内容一字不差的复制到你的环境中，并且只修改apikey，如果依旧存在错误，再提供完整报错（包含Traceback），你的环境信息，源码进行提问

**Comment by chatanywhere** [comment]
> 我之前发给你的那个代码是一个测试open aiAPI连接的代码，这个测试代码显示openai.completion.creat函数有点问题，然后在运行我原本要使用这个openAI key的代码时，completion函数再次出现了问题。并且如上一邮件所说试了所有url还是报错。在另一个显示日志的测试连接的代码当中，显示的是没办法连接上你们给的这个base的网站，错误码404。这就说明 在API连接时就出了问题，连接的问题是key和base的问题吗？还是其他原因？如果你觉得这个问题很简单很好解决，麻烦给出具体的解决方案
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sun, Apr 7, 2024 20:11 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [chatanywhere/GPT_API_free] An error occurred while testing GPTAPI connection: 'str' object has no attribute 'get' (Issue #208) 从一开始你就在提问completion模型为什么报错，我以为是项目的README以及demo只提供了chat模型（gpt）的使用方法，而没有提供completion模型的相关参考，导致你在使用completion模型时遇到了麻烦。因此，我按照你的需求提供了参考代码，我并不知道你是付费用户还是免费用户。而你所需要的_“你得给我一个能用来测试连接免费API的测试代码“_，项目中的demo.py文件已经提供并附有相对完整的注释。 个人认为，非疑难问题，仔细阅读一遍README或许比在issues中提问更加节省时间。 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

首先，你一开始提供的源码是最初的openai包适配的，已经有很多特性被openai弃用，我也和你说了让你升级，另外，你这个测试代码调用的是免费key所不支持的davinci模型，而README也说的很清楚，免费只支持gpt以及embedding模型。
其次，你说的404错误码，他仅仅只是个错误码而已，模型不存在也会返回404。而既然已经有了返回结果，那显然连接已经建立并且服务器做出的响应，你后来使用api.chatanywhere.cn域名时，才是你说的API连接就出现了问题，报错为 Failed to establish a new connection

**Comment by chatanywhere** [comment]
我给你梳理一下啊
首先 你给我了你第一版出问题的源码，我给你的修改意见，并让你阅读官方文档，但你没有看清楚.cn的域名是不支持境内使用的，所以出现了无法连接的问题。
因此，我直接根据你的第一版源码的需求（我理解的需求是你要用davinci模型）给你提供了能直接运行的代码，并且，你测试后也确实没有问题，出现的问题是因为免费key不支持davinci模型，报错也很明确。
这时，你开始质问我为何给你的测试代码怎么都要用付费的，啊 我直接懵逼，我哪知道你要用免费的，我是照着你代码改的啊，主要是，测试代码明明项目里已经有了，我觉得你应该是要用其他模型不会用。但我依旧给你解释了为什么给你这段代码，并告诉你，你要的免费key测试代码demo.py就是。
接着，一小时前，你向我表达了你的不满，告诉我你试了很多，依旧报错 'str' object has no attribute 'get'，但，到现在为止，我依旧没看到你后来参考demo.py修改后的源码，我还是不知道你问题出在哪里

**Comment by good-good-studyy** [comment]
不好意思，我就是个本科生，初次接触这些确实不太熟悉，但你有必要回答个技术问题就这么高人一等贬低他人的吗？请问你是哪里的技术人员？真是有素质



---Original---
From: ***@***.***&gt;
Date: Mon, Apr 8, 2024 00:08 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chatanywhere/GPT_API_free] An error occurred while testing GPTAPI connection: 'str' object has no attribute 'get' (Issue #208)




 
我给你梳理一下啊
 首先 你给我了你第一版出问题的源码，我给你的修改意见，并让你阅读官方文档，但你没有看清楚.cn的域名是不支持境内使用的，所以出现了无法连接的问题。
 因此，我直接根据你的第一版源码的需求（我理解的需求是你要用davinci模型）给你提供了能直接运行的代码，并且，你测试后也确实没有问题，出现的问题是因为免费key不支持davinci模型，报错也很明确。
 这时，你开始质问我为何给你的测试代码怎么都要用付费的，啊 我直接懵逼，我哪知道你要用免费的，我是照着你代码改的啊，主要是，测试代码明明项目里已经有了，我觉得你应该是要用其他模型不会用。但我依旧给你解释了为什么给你这段代码，并告诉你，你要的免费key测试代码demo.py就是。
 接着，一小时前，你向我表达了你的不满，告诉我你试了很多，依旧报错 'str' object has no attribute 'get'，但，到现在为止，我依旧没看到你后来参考demo.py修改后的源码，我还是不知道你问题出在哪里

**Comment by QWXL** [comment]
就目前谈论的内容而言，我没有看到这位官方工作人员有什么直接或间接的对你进行贬低、人身攻击等行为有出现，不熟悉可以理解，但仗着自己不熟悉还反咬一口是不是有点离谱了

**Comment by chatanywhere** [comment]
没有贬低你的意思，而且我认为在issues中进行高质量的提问是很好的，但如同聊天一般的提问显然不适合出现在issues中，这对你来说很浪费时间，对其他人来说，这个issues也给不了他们帮助。项目本身也给出了合适的提问模板，我认为，如果你每次遇到新的报错，都能直接提供源码+报错+环境，你的问题应该很快解决了。
这个issues戾气太重，没有太大的意义，我会删除，后续有问题你可以联系我qq 1227736795。
