### ISSUE TITLE
wrong api key

### ISSUE THREAD

**Issue by NickYi1990** [chatanywhere/GPT_API_free#21]
after I run code in the [demo](https://github.com/chatanywhere/GPT_API_free/blob/main/demo.py) , the error pop up (False, 'OpenAI API 异常: HTTP code 401 from API (wrong api key\n)'), my setting are
```python
openai.api_key = "sk-0PfcSdT723UR44igwVxvEWvLoZJgi0FJyZWy0WCCATp5ka2a"
openai.api_base = "https://api.chatanywhere.com.cn/v1"
```
has anyone encounter this problem also?

**Comment by chatanywhere** [comment]
Due to malicious usage of our previous free API, we have updated the method for obtaining the API Key. Please read the README to obtain the new API Key.
