### ISSUE TITLE
Langchain中如何调用GPT API代理？

### ISSUE THREAD

**Issue by PonnnyWang** [chatanywhere/GPT_API_free#211]
代码如下：
“
from openai import OpenAI

client = OpenAI(
    api_key="sk-xxx",
    base_url="https://api.chatanywhere.tech/v1"
)

index = VectorstoreIndexCreator(
    vectorstore_cls=DocArrayInMemorySearch
).from_loaders([loader])
”

bug如下：
“
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter. (type=value_error)
”

**Comment by chatanywhere** [comment]
建议设置环境变量，参考[python-openai官方库使用](https://github.com/chatanywhere/GPT_API_free?tab=readme-ov-file#python-openai官方库使用autogptlangchain等)方法二

**Comment by PonnnyWang** [comment]
已更改调用API方式为环境变量，代码如下：
`import os
from openai import OpenAI
from langchain.indexes import VectorstoreIndexCreator
from dotenv import load_dotenv, find_dotenv

_ = load_dotenv(find_dotenv())

client = OpenAI(
    api_key=os.environ.get("OPENAI_API_KEY"),
    base_url="https://api.chatanywhere.tech/v1"
)

index = VectorstoreIndexCreator(
    vectorstore_cls=DocArrayInMemorySearch,
).from_loaders([loader])`

其中client可以正常使用，使用langchain的VectorstoreIndexCreator库时报连接异常错误，但是不能像client那样加入 base_url。这种情况有解决方案吗？

**Comment by chatanywhere** [comment]
你似乎搞错了
重点是要设置baseURL的环境变量的
![image](https://github.com/chatanywhere/GPT_API_free/assets/111742565/e79bd666-132c-4860-8d7b-3ee76f4d3b5d)

**Comment by PonnnyWang** [comment]
已解决，感觉解答！
