### ISSUE TITLE
我的key今天还没被成功调用过，就报429错误了

### ISSUE THREAD

**Issue by zhaobudaomingzi** [chatanywhere/GPT_API_free#212]
额度也是减去的

![屏幕截图 2024-04-10 232223](https://github.com/chatanywhere/GPT_API_free/assets/54617500/5fee276e-49a8-4f3b-b2bf-a715cf2f33d0)
![屏幕截图 2024-04-10 232333](https://github.com/chatanywhere/GPT_API_free/assets/54617500/54fc859d-2064-47f2-93a7-896bc9f4f845)

**Comment by chatanywhere** [comment]
1. 额度负数是正常的，因为你的免费账号没有余额
2. 这边查询你提问的这个账号下的key限速原因是ip限速，被限速的ip查询属于cloudflare，估计你利用cf进行了反代中转或者你用的是别人搭建的中转站别人用了cf之类的，建议直连进行访问，避免使用cf之类的公共ip中转访问导致被限速

**Comment by zhaobudaomingzi** [comment]
> 1. 额度负数是正常的，因为你的免费账号没有余额
> 2. 这边查询你提问的这个账号下的key限速原因是ip限速，被限速的ip查询属于cloudflare，估计你利用cf进行了反代中转或者你用的是别人搭建的中转站别人用了cf之类的，建议直连进行访问，避免使用cf之类的公共ip中转访问导致被限速

我是在vercel部署的lobe-chat调用的，然后lobe-chat绑定了cf托管的域名，但没有反代。昨天我在手机和平板都使用过，开了clash

**Comment by zhaobudaomingzi** [comment]
> 1. 额度负数是正常的，因为你的免费账号没有余额
> 2. 这边查询你提问的这个账号下的key限速原因是ip限速，被限速的ip查询属于cloudflare，估计你利用cf进行了反代中转或者你用的是别人搭建的中转站别人用了cf之类的，建议直连进行访问，避免使用cf之类的公共ip中转访问导致被限速

请问是ip限速，而不是请求次数达到每天150次限制的问题吗？

**Comment by chatanywhere** [comment]
vercel也是一样的，也是公用的ip，限速是key+ip一起限速，具体如下：
> 免费API Key限制150请求/24小时/IP&Key调用频率，也就是说你如果在一个IP下使用多个Key，所有Key的每24小时请求数总和不能超过150；同理，你如果将一个Key用于多个IP，这个Key的每24小时请求数也不能超过150。

所以如果你用公用ip，因为别人也用呢，那不是很容易被限速嘛

**Comment by zhaobudaomingzi** [comment]
> 所以如果你用公用ip，因为别人也用呢，那不是很容易被限速嘛

那么如果我想继续在网页端调用模型，有什么办法可以避免使用公共ip吗？

**Comment by chatanywhere** [comment]
不要用vercel 自己服务器部署即可
