### ISSUE TITLE
2024.4.18号，国内使用代理地址明显变慢了

### ISSUE THREAD

**Issue by linux-y** [chatanywhere/GPT_API_free#216]
2024.4.18号，国内使用代理地址明显变慢了
之前响应速度一直是很好的
不知道是暂时的BUG，还是有相关限制了

**Comment by chatanywhere** [comment]
你说的速度慢的是否是免费API，近期我们将在免费内测API上测试官网逆向API，届时免费版API的GPT3.5系列模型可能在官方原生接口与官网逆向接口不定时切换，官网逆向接口相比官方原生接口在某些方面回答可能更聪明，但不支持function且**响应速度可能偶尔较慢**。在测试期间，如果您遇到问题，可以加群联系我们。

付费API依旧使用官方原生接口没有任何变动，响应速度应该不会有变化

**Comment by EasonU-87** [comment]
2024/4/29
免费的api确实回答的响应速度跟流畅度降低了，请问是因为使用时间长了吗？还是其他原因？

**Comment by chatanywhere** [comment]
是的，免费API现在采用逆向方案，确实在速度方面不如之前官方原生的API，主要是成本考虑，现在实在无法承担起继续免费提供高速官方原生API，另外近期处于测试阶段，未来我们会尽可能加快响应速度，如果对响应速度以及稳定性有较高要求可以使用**付费API**。

**Comment by chatanywhere** [comment]
但免费gpt-4依旧采用和付费版本一样的官方原生API方案，保证稳定性和速度，应该不会有响应变慢的情况

**Comment by EasonU-87** [comment]
明白了 谢谢
