### ISSUE TITLE
免费账号报错403

### ISSUE THREAD

**Issue by xym003** [chatanywhere/GPT_API_free#218]
代码如下：
`import os
from langchain.chains import LLMChain
from langchain_core.prompts import PromptTemplate
from langchain_openai import OpenAI

template = """Question: {question}
Answer: Let's think step by step."""

prompt = PromptTemplate.from_template(template)

api_key = "---"#正确输入了
api_base = "https://api.chatanywhere.tech/v1"
llm = OpenAI(api_key=api_key, base_url=api_base,model_name="gpt-3.5-turbo")

llm_chain = LLMChain(prompt=prompt, llm=llm)
question = "What NFL team won the Super Bowl in the year Justin Beiber was born?"

llm_chain.invoke(question)`
我看到项目简介里是支持langchain的，为什么会一直报403错误呢？是不支持langchain的分包吗？
恳请解答

**Comment by ynpl** [comment]
这个用了不是免费的模型了 它里面还用了其他的模型 应该是
