### ISSUE TITLE
请问这个key支持openai.Completion.create接口吗 

### ISSUE THREAD

**Issue by junglekiller14** [chatanywhere/GPT_API_free#220]
因为我需要跑一个代码，代码里的openai版本是0.20.0.只能支持图里的这种调用方式。
![image](https://github.com/chatanywhere/GPT_API_free/assets/91357221/056f8b96-c22d-41ec-885d-df1b95309cb5)

**Comment by chatanywhere** [comment]
应该是openai.ChatCompletion.create
