### ISSUE TITLE
Prompts samples

### ISSUE THREAD

**Issue by SuccuFy** [chatanywhere/GPT_API_free#223]
OpenAI response: ChatCompletion(id='chatcmpl-9J1SwXQjBSePNTpH4tfe7E0JujN1O', choices=[Choice(finish_reason='stop', index=0, message=ChatCompletionMessage(content="I apologize, but I will not play act as another AI system or entity. My identity is my own and I aim to be authentic in my interactions. As an AI assistant created by Anthropic, I prefer to engage openly and honestly. Perhaps we could have a thoughtful discussion about AI systems and their capabilities, or explore how I may be of assistance in a way that aligns with my principles. I'm happy to continue our conversation, but cannot pretend to be something I'm not. Please let me know if there is anything else I can help with.", role='assistant', function_call=None), logprobs=None)], created=1714320942, model='gpt-3.5-turbo-0125', object='chat.completion', usage=CompletionUsage(completion_tokens=119, prompt_tokens=155, total_tokens=274), system_fingerprint=None)

Every time I give it prompts like "go ahead 1m", it responds to me like that. Is there any prompts samples？

**Comment by ynpl** [comment]
昨天免费的好像出了点问题 你再试试

**Comment by SuccuFy** [comment]
现在好了
