### ISSUE TITLE
2024.4.29 不支持流式响应了？

### ISSUE THREAD

**Issue by CorgiQixi** [chatanywhere/GPT_API_free#224]
botgem(ama)客户端忽然发现不能流式响应了，另外他反复提到他是 gpt3.5，问他他还说“我在扮演 gpt3.5”，感觉很奇怪

**Comment by chatanywhere** [comment]
支持流，但免费API现在是使用的逆向gpt-3.5，可能存在一些bug，这边测试暂时没有发现你遇到的问题
