### ISSUE TITLE
OpenAI response: content=None

### ISSUE THREAD

**Issue by SuccuFy** [chatanywhere/GPT_API_free#225]
[chatgpt-2] [INFO] [1714441451.996533728] [chatgpt]: Input message received: Go ahead for 1 m.
[chatgpt-2] [INFO] [1714441452.002544928] [chatgpt]: Chat history updated with {'role': 'user', 'content': 'Go ahead for 1 m.'}
[chatgpt-2] [INFO] [1714441452.006633129] [chatgpt]: Sending messages to OpenAI: [{'role': 'system', 'content': ''}, {'role': 'user', 'content': 'Go ahead for 1 m.'}]
[chatgpt-2] [INFO] [1714441466.389632728] [chatgpt]: OpenAI response: ChatCompletion(id='chatcmpl-wikbJwGK3aIbUzlVph3CqI5iu2RiB', choices=[Choice(finish_reason='function_call', index=0, message=ChatCompletionMessage(content=None, role='assistant', function_call=FunctionCall(arguments='{"angular_x":0,"angular_y":0,"angular_z":0,"duration":10,"linear_x":1,"linear_y":0,"linear_z":0,"robot_name":"turtle1"}', name='publish_cmd_vel')), logprobs=None)], created=1714441464, model='gpt-3.5-turbo-0125', object='chat.completion', usage=CompletionUsage(completion_tokens=51, prompt_tokens=229, total_tokens=280), system_fingerprint=None)
在将信息传输给openai的过程中，openai返回的content=none，我很好奇，于是查询了使用日志
![image](https://github.com/chatanywhere/GPT_API_free/assets/102647612/7fb2900e-04c2-417b-8fa1-7336dce86c49)
说明我都成功调用了，于是又查询余额
![image](https://github.com/chatanywhere/GPT_API_free/assets/102647612/16b00ece-cd34-4fcd-817c-a43a373ddb94)
这是否代表着我欠费呢？但如果是这样的话，前几次虽然调用了api并且产生扣费但是输出却是none是怎么回事呢？有人遇到类似的情况吗？

**Comment by chatanywhere** [comment]
免费API不要参考查询页面的余额，都是负数，不存在余额不足的问题，看你的日志似乎使用了functions call，从一周前我们免费的gpt-3.5模型采用了逆向方案，不再支持functions call，如果需要使用functions可以使用付费API

**Comment by SuccuFy** [comment]
![image](https://github.com/chatanywhere/GPT_API_free/assets/102647612/44918e4c-26fe-4081-b1b9-3ffa696f2f21)
请问哪个可以支持functions call呢？

**Comment by chatanywhere** [comment]
都是支持的

**Comment by chatanywhere** [comment]
区别是key里余额不同

**Comment by SuccuFy** [comment]
购买后除了要更换apikey还要做其他操作吗？我在代码中更换成了购买的apikey但是仍然报一样的错，检测新购买的apikey的用量发现为0，发现仍在调用之前免费版本的apikey。

**Comment by chatanywhere** [comment]
不需要其他操作 你要是没切过来一定是你程序的问题了 key之间是相互独立不相关的 
你检查一下是不是配置文件之类的调整的不对 或者实在没办法试试卸载重新安装你的程序

**Comment by SuccuFy** [comment]
好的我再试试

**Comment by SuccuFy** [comment]
> 不需要其他操作 你要是没切过来一定是你程序的问题了 key之间是相互独立不相关的 你检查一下是不是配置文件之类的调整的不对 或者实在没办法试试卸载重新安装你的程序

现在确实调用的是3.5-0613版本，检查了也是用的付费版apikey，但是content依旧是none，具体报错：
[chatgpt-2] [INFO] [1714547665.740723036] [chatgpt]: Input message received: Go ahead for 1 m.
[chatgpt-2] [INFO] [1714547665.741205092] [chatgpt]: Chat history updated with {'role': 'user', 'content': 'Go ahead for 1 m.'}
[chatgpt-2] [INFO] [1714547665.741734224] [chatgpt]: Sending messages to OpenAI: [{'role': 'system', 'content': ''}, {'role': 'user', 'content': 'Go ahead for 1 m.'}]
[chatgpt-2] [INFO] [1714547667.421556305] [chatgpt]: OpenAI response: ChatCompletion(id='chatcmpl-9JySY03e0v3pzuCMMEFYY6sXwtuLu', choices=[Choice(finish_reason='function_call', index=0, message=ChatCompletionMessage(content=None, role='assistant', function_call=FunctionCall(arguments='{\n  "robot_name": "turtle1",\n  "duration": 1,\n  "linear_x": 1,\n  "linear_y": 0,\n  "linear_z": 0,\n  "angular_x": 0,\n  "angular_y": 0,\n  "angular_z": 0\n}', name='publish_cmd_vel')), logprobs=None)], created=1714547666, model='gpt-3.5-turbo-0613', object='chat.completion', usage=CompletionUsage(completion_tokens=73, prompt_tokens=229, total_tokens=302), system_fingerprint=None)
[chatgpt-2] [INFO] [1714547667.422227635] [chatgpt]: OpenAI response type: FUNCTION CALL

**Comment by chatanywhere** [comment]
仔细看了一下你这个日志并不是报错呀，你看function字段是有返回的，content是none应该并没有问题

**Comment by SuccuFy** [comment]
嗯确实是有function字段返回，主要是我没有放全，报错是在后面的内容：
[chatgpt-2] [INFO] [1714547667.422227635] [chatgpt]: OpenAI response type: FUNCTION CALL
[chatgpt-2] [INFO] [1714547667.422854109] [chatgpt]: Get message from OpenAI: ChatCompletionMessage(content=None, role=&apos;assistant&apos;, function_call=FunctionCall(arguments=&apos;{\n  &quot;robot_name&quot;: &quot;turtle1&quot;,\n  &quot;duration&quot;: 1,\n  &quot;linear_x&quot;: 1,\n  &quot;linear_y&quot;: 0,\n  &quot;linear_z&quot;: 0,\n  &quot;angular_x&quot;: 0,\n  &quot;angular_y&quot;: 0,\n  &quot;angular_z&quot;: 0\n}&apos;, name=&apos;publish_cmd_vel&apos;)), type: &lt;class &apos;openai.types.chat.chat_completion_message.ChatCompletionMessage&apos;&gt;
[chatgpt-2] [INFO] [1714547667.423417189] [chatgpt]: Get content from OpenAI: None, type: &lt;class &apos;NoneType&apos;&gt;
[chatgpt-2] [INFO] [1714547667.423961078] [chatgpt]: Get function call from OpenAI: FunctionCall(arguments=&apos;{\n  &quot;robot_name&quot;: &quot;turtle1&quot;,\n  &quot;duration&quot;: 1,\n  &quot;linear_x&quot;: 1,\n  &quot;linear_y&quot;: 0,\n  &quot;linear_z&quot;: 0,\n  &quot;angular_x&quot;: 0,\n  &quot;angular_y&quot;: 0,\n  &quot;angular_z&quot;: 0\n}&apos;, name=&apos;publish_cmd_vel&apos;), type: &lt;class &apos;openai.types.chat.chat_completion_message.FunctionCall&apos;&gt;
[chatgpt-2] [INFO] [1714547667.424676152] [chatgpt]: Chat history updated with {&apos;role&apos;: &apos;assistant&apos;, &apos;content&apos;: None, &apos;function_call&apos;: FunctionCall(arguments=&apos;{\n  &quot;robot_name&quot;: &quot;turtle1&quot;,\n  &quot;duration&quot;: 1,\n  &quot;linear_x&quot;: 1,\n  &quot;linear_y&quot;: 0,\n  &quot;linear_z&quot;: 0,\n  &quot;angular_x&quot;: 0,\n  &quot;angular_y&quot;: 0,\n  &quot;angular_z&quot;: 0\n}&apos;, name=&apos;publish_cmd_vel&apos;)}
[chatgpt-2] Traceback (most recent call last):
[chatgpt-2]   File &quot;/home/fay/ros2_ws/install/llm_model/lib/llm_model/chatgpt&quot;, line 33, in &lt;module&gt;
[chatgpt-2]     sys.exit(load_entry_point(&apos;llm-model&apos;, &apos;console_scripts&apos;, &apos;chatgpt&apos;)())
[chatgpt-2]   File &quot;/home/fay/ros2_ws/build/llm_model/llm_model/chatgpt.py&quot;, line 342, in main
[chatgpt-2]     rclpy.spin(chatgpt)
[chatgpt-2]   File &quot;/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py&quot;, line 222, in spin
[chatgpt-2]     executor.spin_once()
[chatgpt-2]   File &quot;/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py&quot;, line 739, in spin_once
[chatgpt-2]     self._spin_once_impl(timeout_sec)
[chatgpt-2]   File &quot;/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py&quot;, line 736, in _spin_once_impl
[chatgpt-2]     raise handler.exception()
[chatgpt-2]   File &quot;/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py&quot;, line 239, in __call__
[chatgpt-2]     self._handler.send(None)
[chatgpt-2]   File &quot;/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py&quot;, line 437, in handler
[chatgpt-2]     await call_coroutine(entity, arg)
[chatgpt-2]   File &quot;/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py&quot;, line 362, in _execute_subscription
[chatgpt-2]     await await_or_execute(sub.callback, msg)
[chatgpt-2]   File &quot;/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py&quot;, line 107, in await_or_execute
[chatgpt-2]     return callback(*args)
[chatgpt-2]   File &quot;/home/fay/ros2_ws/build/llm_model/llm_model/chatgpt.py&quot;, line 316, in llm_callback
[chatgpt-2]     self.write_chat_history_to_json()
[chatgpt-2]   File &quot;/home/fay/ros2_ws/build/llm_model/llm_model/chatgpt.py&quot;, line 233, in write_chat_history_to_json
[chatgpt-2]     json_data = json.dumps(config.chat_history)
[chatgpt-2]   File &quot;/usr/lib/python3.10/json/__init__.py&quot;, line 231, in dumps
[chatgpt-2]     return _default_encoder.encode(obj)
[chatgpt-2]   File &quot;/usr/lib/python3.10/json/encoder.py&quot;, line 199, in encode
[chatgpt-2]     chunks = self.iterencode(o, _one_shot=True)
[chatgpt-2]   File &quot;/usr/lib/python3.10/json/encoder.py&quot;, line 257, in iterencode
[chatgpt-2]     return _iterencode(o, 0)
[chatgpt-2]   File &quot;/usr/lib/python3.10/json/encoder.py&quot;, line 179, in default
[chatgpt-2]     raise TypeError(f&apos;Object of type {o.__class__.__name__} &apos;
[chatgpt-2] TypeError: Object of type FunctionCall is not JSON serializable
[ERROR] [chatgpt-2]: process has died [pid 4562, exit code 1, cmd &apos;/home/fay/ros2_ws/install/llm_model/lib/llm_model/chatgpt --ros-args -r __node:=chatgpt&apos;].
并且小海龟无动作, 具体报错行 json_data = json.dumps(config.chat_history)也是chatgpt.py里的，所以感觉可能function call返回的还是空？

**Comment by SuccuFy** [comment]
而且之前用的免费版本，duration和linear_x依旧有返回值，按理说是不支持function call的
![6fa457d964f5e3c64865b575dd32f19](https://github.com/chatanywhere/GPT_API_free/assets/102647612/36dac475-814d-4aac-a13a-c4d126e68e16)
所以感觉问题还是在none上

**Comment by chatanywhere** [comment]
这边测试了一下，如果是函数调用，那content必然是none
应该还是你那别函数调用的时候不应该去读取content

另外你说之前免费的函数可以用大概是因为我们这边做了容错，如果逆向报错会使用官方的原生API（可以使用functions的API）回复，所以可能免费的也偶尔可以支持函数响应。

**Comment by SuccuFy** [comment]
好的，谢谢，那我再确定一下代码
