### ISSUE TITLE
不可以使用Langchain连接

### ISSUE THREAD

**Issue by ch3cke** [chatanywhere/GPT_API_free#228]
**Describe the bug 描述bug**
无法使用langchain_openai的OpenAI类连接目标，会爆“{'error': {'message': '免费API限制使用gpt-3.5-turbo，gpt-4 和 embeddings模型，如有更多需求，请访问 https://buyca.shop 购买付费API。The free account is limited to use gpt-3.5-turbo, gpt-4 and embeddings. If you have additional requirements, please visit https://buyca.shop to purchase a premium key.', 'type': 'chatanywhere_error', 'param': None, 'code': '403 FORBIDDEN'}}“

**To Reproduce 复现方法**
代码
```python
from langchain_openai import OpenAI
from utils.storyboard import Storyboard



class GPT_Agent:
    def __init__(self, config):
        self.llm = OpenAI(
            openai_api_key="sk-***",
            openai_api_base="https://api.chatanywhere.tech/v1",
            model_name="gpt-3.5-turbo"
        )

    def ask(self, question):
        response = self.llm.invoke(question)
        return response.content
if __name__ == '__main__':
    a = GPT_Agent(config)
    # print(config)
    a.ask("hello")
``` 

**Screenshots 截图**
<img width="1829" alt="image" src="https://github.com/chatanywhere/GPT_API_free/assets/43578793/74de93cb-99f1-4299-bcee-21e643fd69f9">

**Tools or Programming Language 使用的工具或编程语言**
Describe in detail the GPT tool or programming language you used to encounter the problem
python

**Additional context 其他内容**

**Comment by ynpl** [comment]
from langchain_openai import ChatOpenAI

chat = ChatOpenAI(model="gpt-3.5-turbo", openai_api_base="https://api.chatanywhere.com.cn/v1",
                  openai_api_key="sk-xxxx")
print(chat.invoke("你是谁"))
