### ISSUE TITLE
zotero-gpt中使用出错 提示“Incorrect API key provided"

### ISSUE THREAD

**Issue by Rankizhu** [chatanywhere/GPT_API_free#231]
**Describe the bug 描述bug**
返回API错误

**Screenshots 截图**
![image](https://github.com/chatanywhere/GPT_API_free/assets/154110638/7a21e9af-1d71-4cdc-ae28-f5cdaa5c6061)
**Tools or Programming Language 使用的工具或编程语言**
zotero-gpt

**Comment by ynpl** [comment]
没改api地址 看看文档
