### ISSUE TITLE
token计算问题.app,查询后台,计算示例网页各自的结果都不同.

### ISSUE THREAD

**Issue by icemanstudy** [chatanywhere/GPT_API_free#232]
**Describe the bug 描述bug**
购买了收费api,但是token计算方面很迷.不知道是怎么消耗的.

**To Reproduce 复现方法**
使用的是ChatBox.在这个应用内部有token数量显示.
然后Token计算示例: https://tiktokenizer.vercel.app可以进行查询.
余额和使用记录查询页面也可以查询：https://api.chatanywhere.org/

**Screenshots 截图**
这是app中的
![](https://res.cloudinary.com/xubingok/image/upload/v1715328950/blog/038dd4192f1c429e3457c9c79128a711.png)
这是同样文字复制到计算示例中的.
![](https://res.cloudinary.com/xubingok/image/upload/v1715328971/blog/3aa4054cad585ddf7aff443f4f2fb5d9.png)
这是发生对话后在查询页面查到的.
![](https://res.cloudinary.com/xubingok/image/upload/v1715328991/blog/019c4a9746e288819d3dc8293d93e517.png)

为什么会有这样的区别呢?查询后台中显示消耗的token是最多的.

**Comment by chatanywhere** [comment]
你少算了系统预设，这边用Tiktokenizer算下来差不多
<img width="1163" alt="image" src="https://github.com/chatanywhere/GPT_API_free/assets/111742565/9d78c8e9-24eb-4be6-9f0b-dc69a2e1b434">

**Comment by icemanstudy** [comment]
查询页面的两条都是本次问答消耗的token....187+120=307.差距老多了...
我特意隔了段时间来进行问答的.
系统预设+问题+答案...在查询网页中却有两条调用记录..合起来的token消耗数量非常不符合. @chatanywhere

**Comment by chatanywhere** [comment]
120那个记录应该是chatbox自动增加的一次请求 用来得出该次对话的标题的 也就是你页面显示的TokenCalc那个标题 计费不可能出错 放心就行
