### ISSUE TITLE
[Enhancement]请问能否支持dbever

### ISSUE THREAD

**Issue by sgyt2020** [chatanywhere/GPT_API_free#237]
请问能否支持dbever
![图片](https://github.com/chatanywhere/GPT_API_free/assets/83530976/71575753-c867-4613-8f75-3bffee01db03)

**Comment by sgyt2020** [comment]
这个需要怎么修改代理

**Comment by loukai99** [comment]
我试了似乎无法修改接入点url，暂时应该是无法使用的

**Comment by sgyt2020** [comment]
> 我试了似乎无法修改接入点url，暂时应该是无法使用的

噢噢好的 能不能在.ini文件里面加上url路径

**Comment by chatanywhere** [comment]
可能需要你自己研究一下，这边没有用过dbeaver
