### ISSUE TITLE
现在的价格还有折扣吗？

### ISSUE THREAD

**Issue by pengwon** [chatanywhere/GPT_API_free#240]
请问现在的价格还有折扣吗？
购买时RMB:CA是1:1，调用接口价格CA:官方是7:1，相当于折扣了汇率零头，是这样计算的吗？

**Comment by chatanywhere** [comment]
CA系列模型折扣大，gpt4相当于4:1，gpt3相当于2:1，Azure提供服务，速度稍微慢点，其他都一样
OpenAI官方的服务实在没法提供更高的折扣了
