### ISSUE TITLE
VIP通道响应速度会不会比普通KEY快？

### ISSUE THREAD

**Issue by nathangary** [chatanywhere/GPT_API_free#243]
VIP通道响应速度会不会比普通KEY快？

**Comment by chatanywhere** [comment]
付费Key的响应速度是一样的，都是毫秒级别的响应啊，VIP再快也快不了了啊

**Comment by nathangary** [comment]
流式响应挺快的，但是普通响应就很慢

**Comment by chatanywhere** [comment]
那当然了，AI也是需要时间生成内容的，非流就是生成完再一起返回给你，流就是生成一点返回一点，理论上非流需要等待的时间就是流式响应全部答复完的时间

**Comment by nathangary** [comment]
但是也忒慢了

**Comment by chatanywhere** [comment]
响应速度都由OpenAI决定，这个我们无法解决。
本就是大计算量的东西，响应速度和生成的字数是正相关的，怎么也不能几秒钟就给你生成一长串啊，你说你要是只问个你好，生成几十个字的话，响应应该还是十分快速的
