### ISSUE TITLE
免费API在调用gpt-3.5-turbo时经常返回如下错误，只要gpt试图调用tool call就会这样，如果不调用tool call，直接response就正常

### ISSUE THREAD

**Issue by lewiswu1209** [chatanywhere/GPT_API_free#249]
Error code: 500 - {'error': {'message': 'com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "parameters" (class cn.chatanywhere.openaiapi.entity.chat.Function), not marked as ignorable (2 known properties: "name", "arguments"])\n at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 297] (through reference chain: cn.chatanywhere.openaiapi.entity.chat.ChatCompletionResponse["choices"]->java.util.ArrayList[0]->cn.chatanywhere.openaiapi.entity.chat.ChatChoice["message"]->cn.chatanywhere.openaiapi.entity.chat.Message["tool_calls"]->java.util.ArrayList[0]->cn.chatanywhere.openaiapi.entity.chat.ToolCalls["function"]->cn.chatanywhere.openaiapi.entity.chat.Function["parameters"])', 'type': 'chatanywhere_error', 'param': None, 'code': '500 INTERNAL_SERVER_ERROR'}}

**Comment by chatanywhere** [comment]
请提供一下报错的代码片段以及环境

**Comment by chatanywhere** [comment]
不需要了，已定位问题，6月6日24点前热补丁修复
