### ISSUE TITLE
langchain_openai调用返回403

### ISSUE THREAD

**Issue by duxingxingstar** [chatanywhere/GPT_API_free#250]
**Describe the bug 描述bug**
openai.PermissionDeniedError: Error code: 403 - {'error': {'message': '免费API限制使用gpt-3.5-turbo，gpt-4 和 embeddings模型，如有更多需求，请访问 https://buyca.shop 购买付费API。The free account is limited to use gpt-3.5-turbo, gpt-4 and embeddings. If you have additional requirements, please visit https://buyca.shop to purchase a premium key.', 'type': 'chatanywhere_error', 'param': None, 'code': '403 FORBIDDEN'}}

代码很简单，如下
from dotenv import load_dotenv # 用于加载环境变量
load_dotenv() # 加载 .env 文件中的环境变量
from langchain_openai import OpenAI
llm = OpenAI(model_name="gpt-3.5-turbo" , max_tokens=200)
text = llm.invoke("请给我写一句情人节红玫瑰的中文宣传语")
print(text)

用原生openai调用成功，代码如下
from openai import OpenAI

client = OpenAI(base_url='https://api.chatanywhere.tech/v1')
def generate_response(prompt):
    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": prompt}
            ]
        )
        return response.choices[0].message.content
    except Exception as e:
        return str(e)

if __name__ == "__main__":
    user_prompt = "请给我写一句情人节红玫瑰的中文宣传语"
    response = generate_response(user_prompt)
    print(response)

**Comment by ynpl** [comment]
你这用了不是免费的模型  他用了不是 chat的模型

**Comment by guanzhen580** [comment]
这可能是因为使用了from langchain_openai import OpenAI，实际上应该使用 ChatOpenAI，即只用聊天模型
