### ISSUE TITLE
请问我们支持转发 openai 的 assistants 吗？

### ISSUE THREAD

**Issue by JDChi** [chatanywhere/GPT_API_free#251]
我在创建 assistant 的时候
` 
 assistant = client.beta.assistants.create(
        name="二手商品价格助手",
        instructions="帮我计算一些二手商品的价格",
        tools=[{"type": "code_interpreter"}],
        model="gpt-3.5-turbo",
        response_format={"type": "text"},
    )
`

报错了：
`
openai.NotFoundError: Error code: 404 - {'timestamp': 1718012186335, 'status': 404, 'error': 'Not Found', 'path': '//assistants'}
`

**Comment by JDChi** [comment]
修改标题。

**Comment by ynpl** [comment]
不支持的
