### ISSUE TITLE
用容器安装的微信机器人，在配置文件中设置转发host,没生效。香港服务器centos系统

### ISSUE THREAD

**Issue by fanwujiu130** [chatanywhere/GPT_API_free#252]
**Describe the bug 描述bug**
![360截图20240617082916729](https://github.com/chatanywhere/GPT_API_free/assets/79819602/3e7b3751-e37a-4b9c-80c8-e783ae7e049d)

**To Reproduce 复现方法**

**Screenshots 截图**

**Tools or Programming Language 使用的工具或编程语言**
Describe in detail the GPT tool or programming language you used to encounter the problem

**Additional context 其他内容**

**Comment by ynpl** [comment]
你这很明显改上转发的URL, 建议好好看一下你用的项目的文档, 或者询问项目的开发者如何更改转发URL, 你估计改的代理的Host
