### ISSUE TITLE
AuthenticationError: Error code: 401

### ISSUE THREAD

**Issue by waka45** [chatanywhere/GPT_API_free#256]
**描述bug**
在仓库中申请了免费的api key进行试验，添加环境变量成功了执行了以下代码。

**代码截图**
<img width="472" alt="image" src="https://github.com/chatanywhere/GPT_API_free/assets/35132294/7787bb15-adb5-464c-afea-56cd3dfbb419">

**报错详细信息**

`AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-B9FTN***************************************M6zr. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}`

**Comment by ynpl** [comment]
没改api地址 这个是转发

**Comment by QingjiaTsang** [comment]
> 没改api地址 这个是转发

什么意思，获取到的api key不是直接放环境变量里吗，还是说对api key需要做什么前置的操作
