### ISSUE TITLE
Host不太稳定经常连不上

### ISSUE THREAD

**Issue by hshenmeow** [chatanywhere/GPT_API_free#26]
转发api key对应的两个host感觉都不太稳定，尤其是在用sidebar的时候，经常用着就连不上了，或者回应速度会变得非常慢。同时，感觉转发api的速度比直连官方接口速度会慢不少。不知道是不是host访问量过大的原因？能否优化升级一下呢？谢谢！

**Comment by chatanywhere** [comment]
生成速度由官方服务器决定的，我们的转发服务器负载正常，用动态转发接口按理说只会比用官方的延时更低，毕竟用官方的你得走个梯子，梯子的线路一般来说没我们的线路好，用着用着连不上请检查是不是走梯子了。

**Comment by hshenmeow** [comment]
> 生成速度由官方服务器决定的，我们的转发服务器负载正常，用动态转发接口按理说只会比用官方的延时更低，毕竟用官方的你得走个梯子，梯子的线路一般来说没我们的线路好，用着用着连不上请检查是不是走梯子了。

我在境内境外都测试过转发api，其实感觉两个host都是在境外的延时和稳定性反而更高一些，不过在境外的话速度会肉眼可见比官方接口慢（但确实可以理解），一天可能会断1-3次；境内的话就算用com.cn的服务器也速度较慢而且更加经常断，还挺影响使用体验的。因为很喜欢这个转发的模式，所以希望代理的服务器能够更加稳定一些！不知道是不是可以多设置一些节点？

**Comment by chatanywhere** [comment]
境内com.cn经常断的问题之前似乎没有人反馈过，这个可能不是我们服务器的问题，您说的经常断是什么报错，或者什么现象能具体说明吗。

**Comment by hshenmeow** [comment]
> 境内com.cn经常断的问题之前似乎没有人反馈过，这个可能不是我们服务器的问题，您说的经常断是什么报错，或者什么现象能具体说明吗。

不好意思我这几天并不在境内，不过境外今天正好在sidebar出现了断连的问题，他是这样提示我的：
You exceeded your current quota, please check your plan and billing details.
![image](https://github.com/chatanywhere/GPT_API_free/assets/134988836/2e44d93b-dbee-47d3-a414-8559656a3c02)
但实际额度还有很多，而且过了一段时间就又能使用了，我也不知道怎么回事，如果有其他的提示我再保留好来反馈哈

**Comment by chatanywhere** [comment]
这个问题11点之前修复了哈

**Comment by hshenmeow** [comment]
好的！希望能多多维护，感恩！
