### ISSUE TITLE
余额查询的网页访问错误

### ISSUE THREAD

**Issue by toboto** [chatanywhere/GPT_API_free#267]
**Describe the bug 描述bug**
余额查询的页面，[https://api.chatanywhere.tech](https://api.chatanywhere.tech)，访问错误
<img width="1332" alt="image" src="https://github.com/user-attachments/assets/cba0d80f-636a-4b49-a390-d48e99528065">

**Comment by ynpl** [comment]
余额查询 https://api.chatanywhere.org/
