### ISSUE TITLE
可以使用GPT-4o mini吗？怎么使用？

### ISSUE THREAD

**Issue by LimbaHub** [chatanywhere/GPT_API_free#269]

**Comment by chatanywhere** [comment]
已支持，正常调用即可，接口定义与其他模型相同

**Comment by sunsetzks** [comment]
> 已支持，正常调用即可，接口定义与其他模型相同

请问下gpt-4o mini的图片怎么算token的，我刚才试了一下，一张小图片，用了14k的token，

**Comment by chatanywhere** [comment]
gpt-4o-mini的价格并没有降低，与gpt-4o一致，因为mini的token价格为4o的33分之一，所以你应该会看到图片的token计算是4o的33倍，具体参考openai官方的价格页面https://openai.com/api/pricing/

**Comment by chatanywhere** [comment]
gpt-4o-mini的图片价格并没有降低，与gpt-4o一致，因为mini的单token价格为4o的33分之一，所以你应该会看到图片的token计算是4o的33倍，具体参考openai官方的价格页面https://openai.com/api/pricing/

**Comment by SAnBlog** [comment]
> gpt-4o-mini的图片价格并没有降低，与gpt-4o一致，因为mini的单token价格为4o的33分之一，所以你应该会看到图片的token计算是4o的33倍，具体参考openai官方的价格页面https://openai.com/api/pricing/

那纯文本4o mini token的价格你这边是多少?对比4o下降了多少?

**Comment by kiradzS** [comment]
mini价格1块钱1m，更官网价格一样，这比deepbricks贵多了啊，首页上说的几折几折具体是哪些方面打折啊

**Comment by zyoung1212** [comment]
> 已支持，正常调用即可，接口定义与其他模型相同

请问gpt-4o-mini支持高并发吗？

**Comment by chatanywhere** [comment]
支持高并发
