### ISSUE TITLE
基于langchain调用openai会显示openai.error.AuthenticationError: Incorrect API key provided

### ISSUE THREAD

**Issue by Gooseeeeeeeeeeeeee** [chatanywhere/GPT_API_free#274]
有没有大佬帮忙解决一下，url也改了，梯子也试了好多个，付费和免费的api一律说incorrect
完整代码如下：import os
from langchain.chat_models import ChatOpenAI
#原代码中为正常api
os.environ["OPENAI_API_KEY"] = "sk-yjVQW***************************************p76Y"

chat = ChatOpenAI(
    openai_api_key=os.environ["OPENAI_API_KEY"],
    model='gpt-3.5-turbo',
    base_url="https://api.chatanywhere.tech/v1"
)

from langchain.schema import (
    SystemMessage,
    HumanMessage,
    AIMessage
)

messages = [
    SystemMessage(content="You are a helpful assistant."),
    HumanMessage(content="Knock knock."),
    AIMessage(content="Who's there?"),
    HumanMessage(content="Orange"),

]
res = chat(messages)
print(res)

**Comment by Gooseeeeeeeeeeeeee** [comment]
测试过如果是from openai import OpenAI的话是完全可以正常使用的，langchain你很高傲吗:(

**Comment by Gooseeeeeeeeeeeeee** [comment]
对不起，是openai的版本太低了，按照某教程配置的，没想到一开始环境就出错了，丢人
帖子不删了，给各位兄弟一个前车之鉴。
参考正常使用的版本：
langchain--0.2.11
langchain-community--0.2.10
openai--1.37.1

**Comment by xinxinlaoshi** [comment]
我用的 1.41.0的也不行
