### ISSUE TITLE
不太清楚設置哪裡有問題了 測試不過

### ISSUE THREAD

**Issue by GABBYY270** [chatanywhere/GPT_API_free#276]
![image](https://github.com/user-attachments/assets/2fe191e7-a2a1-483e-a38e-f9abf46fa658)

**Comment by GABBYY270** [comment]
![image](https://github.com/user-attachments/assets/9af3c639-cbf1-469b-ab26-f80b0bb7d155)
感覺應該是要這樣設置? 但還是沒法通過測試APIKEY

**Comment by ynpl** [comment]
第二个程序 你没详细的报错看出不出

**Comment by chatanywhere** [comment]
> 這款把模型換成gpt-4o-mini 就能用了(但用沒五分鐘就又停了)
每日有使用限制，跑翻译一般不太够用，建议付费版
