### ISSUE TITLE
作者您好，我想咨询一下，zotero的翻译插件用chatgp的api，现在还是3.5-turbo的模型吗，因为我想从您这买4o-mini的key，但不知道能不能用，谢谢

### ISSUE THREAD

**Issue by rookiego1** [chatanywhere/GPT_API_free#279]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ynpl** [comment]
可以
