### ISSUE TITLE
国内镜像挂了

### ISSUE THREAD

**Issue by gt-tool** [chatanywhere/GPT_API_free#28]
网站挂了，404：https://api.chatanywhere.com.cn/

**Comment by chatanywhere** [comment]
没挂，404你配置有问题，你用的软件后面估计要加v1

**Comment by chatanywhere** [comment]
没挂，404应该是你配置有问题

**Comment by forchannot** [comment]
![image](https://github.com/chatanywhere/GPT_API_free/assets/100580891/d67324d4-a2a4-4ff4-8c56-db1a0f6db169)
我这里也是404

**Comment by loukai99** [comment]
> ![image](https://user-images.githubusercontent.com/100580891/242576596-d67324d4-a2a4-4ff4-8c56-db1a0f6db169.png)
> 我这里也是404

你这样直接打开难道不应该是404吗，不然应该是什么

**Comment by chatanywhere** [comment]
README里面也没有说这个可以查询余额啊

**Comment by gt-tool** [comment]
镜像没挂，404的都是使用的问题，检查一下使用方式
