### ISSUE TITLE
希望加入模型微调功能

### ISSUE THREAD

**Issue by Exploding-Soda** [chatanywhere/GPT_API_free#280]
最近一两个礼拜注意到OpenAI开始允许以gpt4o mini为基底来进行finetune自己的模型了。
阅读官方文档后注意到OpenAI是有提供允许用户使用API的形式来finetune自己的模型的，不知道未来有计划加入finetune的功能吗？

**Comment by ynpl** [comment]
转发api 是实现不了微调的!
