### ISSUE TITLE
Zotero GPT插件只能输出一个汉字

### ISSUE THREAD

**Issue by Wang-Ling-jie** [chatanywhere/GPT_API_free#281]
![image](https://github.com/user-attachments/assets/78670d44-b69c-4ac2-b92d-8fa380bb3e36)
![image](https://github.com/user-attachments/assets/744c608c-0ad5-47ea-87e9-b032e3d6395c)
![image](https://github.com/user-attachments/assets/259ccc97-d2f8-425f-a6bf-6dd930cff227)

zotero版本是7.0.1，Awesome GPT版本是1.1.7，使用的API key是免费版，无论是AskPDF，Translate还是AskZotero都只有一个汉字（或英文字母）输出

**Comment by hyliush** [comment]
同样的问题，更换GPT4后正常输出。调用记录如下：
![image](https://github.com/user-attachments/assets/905e7551-1432-4202-8f4d-893adef44a62)

**Comment by Wang-Ling-jie** [comment]
> 同样的问题，更换GPT4后正常输出。调用记录如下： ![image](https://private-user-images.githubusercontent.com/49185490/358612445-905e7551-1432-4202-8f4d-893adef44a62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTg1ODcsIm5iZiI6MTcyMzgxODI4NywicGF0aCI6Ii80OTE4NTQ5MC8zNTg2MTI0NDUtOTA1ZTc1NTEtMTQzMi00MjAyLThmNGQtODkzYWRlZjQ0YTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDE0MjQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZDYwZjkzNmIyYWI5MDg1NTNmMGM5NTVlYzI0YjViZjJiNjVkMjA5MDRlNTI4Yzc0NDkxNDU1YjIzMWIxMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yLjc1ITI7-7EdIjkCoZYlbFEkq0RU_8YLQ90-60xCME)

同样换用gpt-4和gpt-4o-mini已解决，顺便问一下这个调用记录在哪里查的？

**Comment by hyliush** [comment]
https://api.chatanywhere.tech/#/      应该是API Key的问题，用同学的key输出正常

**Comment by chatanywhere** [comment]
问题已修复
