### ISSUE TITLE
Clarification Needed on Using cn Endpoint for Overseas Users

### ISSUE THREAD

**Issue by cubxxw** [chatanywhere/GPT_API_free#285]
转发Host1: https://api.chatanywhere.tech (国内中转，延时更低)
转发Host2: https://api.chatanywhere.cn (国外使用,国内需要全局代理)

不理解 ！ 这里容易误导，为什么海外用 cn

**Comment by ynpl** [comment]
这个注释写的很清楚. 只要看了就不会的

**Comment by cubxxw** [comment]
@ynpl 不是注释的问题

```go
var a = 200 // a 表示最大链接数
```

懂吗

**Comment by ynpl** [comment]
这只是个域名, 服务器在国外!  况且已经说明了国外使用. 
没有谁规定了.cn的必须在国内才能使用! 
就像你上面写的
var a = 200 // a 表示最大链接数
注释已经写的非常清楚了, 看不懂那是看的人有问题!

**Comment by chatanywhere** [comment]
> 转发Host1: https://api.chatanywhere.tech (国内中转，延时更低) 转发Host2: https://api.chatanywhere.cn (国外使用,国内需要全局代理)
> 
> 不理解 ！ 这里容易误导，为什么海外用 cn

一些历史原因导致的海外用cn，确实不太合理，但现阶段因为有存量用户，换过来也不太现实
