### ISSUE TITLE
zotero翻译插件和iTerm均出现405报错

### ISSUE THREAD

**Issue by JYDAG** [chatanywhere/GPT_API_free#286]
**Describe the bug 描述bug**
确定配置没有问题，zotero- translator和iTerm出现405报错，沉浸式翻译可以正常使用，.tech和.cn都出现此问题

**Screenshots 截图**
<img width="467" alt="image" src="https://github.com/user-attachments/assets/49d4df98-e63b-4fad-9b10-209dfe1875a0">

<img width="248" alt="image" src="https://github.com/user-attachments/assets/fae94560-42bb-4a17-9364-3ab1f1d0fa13">

**Comment by wang1595** [comment]
你好，请问你解决了吗？我也出现405的错误

**Comment by chatanywhere** [comment]
请提供zetero和iterm的版本以及插件版本

**Comment by JYDAG** [comment]
### 补充：
- Zotero 7.0.1
- Translate for Zotero 2.0.0
- iTerm2 Build 3.5.4
- iTerm AI plugin 1.0(1)

**Comment by chatanywhere** [comment]
url配置错误
应该是 https://api.chatanywhere.tech/v1/chat/completions

**Comment by JYDAG** [comment]
已解决，谢谢
