### ISSUE TITLE
 能不能用于api.openai.com 

### ISSUE THREAD

**Issue by MrGongqi** [chatanywhere/GPT_API_free#3]
要是科学上网的话，host能不能写成api.openai.com 呢

**Comment by chatanywhere** [comment]
当然不行啦 这是反代key 向官方请求必然报错

**Comment by MrGongqi** [comment]
请问一下，，这个反代API和openai的chatgpt有啥区别，，，反代api是通过反向代理间接联入到chatgpt吗？就是我想知道两者是不是一样的东西

**Comment by chatanywhere** [comment]
对的 直接反代到官方接口
