### ISSUE TITLE
状态码401 报错信息是这个样子，究竟是什么问题？是国内无法用吗

### ISSUE THREAD

**Issue by 1564342813** [chatanywhere/GPT_API_free#304]
with status code 401:</p>
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>401 Authorization Required</title></head>
<body>
<h1>401 Authorization Required</h1>
<p>This server could not verify that you are authorized to access the
document requested.<hr/>Powered by Tengine</body>
</html>
<p>如果是网络问题，建议优化网络，比如打开/切换代理等。</p>
<p><code>api</code> https://api.chatanywhere.com.cn/<br/>
<code>secretkey</code>Vx2...N8Wi<br />
<code>model</code>gpt-3.5-turbo-0125<br/>
<code>temperature</code>0.4</p>

**Comment by chatanywhere** [comment]
key没写全，前面的sk-呢在 2024年10月10日，15:21，small bei ***@***.***> 写道：﻿
with status code 401:


<title>401 Authorization Required</title>

401 Authorization Required
This server could not verify that you are authorized to access the
document requested.Powered by Tengine

如果是网络问题，建议优化网络，比如打开/切换代理等。
api https://api.chatanywhere.com.cn/
secretkeyVx2...N8Wi
modelgpt-3.5-turbo-0125
temperature0.4

**Comment by 1564342813** [comment]
好的，已解决，感谢。密钥后面只能加一个空格，多了一个空格导致sk传不上去
