### ISSUE TITLE
langChain的OpenAPI使用免费Key时报错403

### ISSUE THREAD

**Issue by jiazhiqiang1977** [chatanywhere/GPT_API_free#309]
我也遇到此错误
代码如下
# 获取 API 密钥
openai_api_key = os.getenv("OPENAI_API_KEY")

# 导入OpenAI
from langchain_openai import OpenAI

# 选择要使用的大模型，并设置自定义API端点
llm = OpenAI(api_key=openai_api_key,base_url= "https://api.chatanywhere.tech/v1", timeout=60, model="gpt-3.5-turbo",temperature=0)  

# 测试 LLM，进行一次简单的文本生成
try:
    # 直接传入字符串作为 prompt
    response = llm.invoke("简单测试：你好，世界！")
    print("模型返回结果：")
    print(response)
except Exception as e:
    print(f"API 调用失败: {e}")
运行后提示为
API 调用失败: Error code: 403 - {'error': {'message': '免费API限制使用gpt-3.5-turbo，gpt-4 和 embeddings模型，如有更多需求，请访问 https://peiqishop.me 购买付费API。The free account is limited to use gpt-3.5-turbo, gpt-4 and embeddings. If you have additional requirements, please visit https://peiqishop.me to purchase a premium key.', 'type': 'chatanywhere_error', 'param': None, 'code': '403 FORBIDDEN'}}
我看介绍说可以支持LangChain呢，是哪里用的不对呢？

_Originally posted by @duxingxingstar in https://github.com/chatanywhere/GPT_API_free/issues/246#issuecomment-2156271428_

**Comment by jiazhiqiang1977** [comment]
具体访问url是这个的时候报的403错误【<Request('POST', 'https://api.chatanywhere.tech/v1/completions')>】
![image](https://github.com/user-attachments/assets/0af11167-5f82-4fb1-8bcb-151eb4a503c0)

**Comment by ynpl** [comment]
你代码写的有问题
要用chat 你是补全了
from langchain_openai import ChatOpenAI

chat = ChatOpenAI(model="gpt-3.5-turbo", openai_api_base="https://api.chatanywhere.tech/v1",
                  openai_api_key="sk-xxxxx")
print(chat.invoke("你是谁"))

**Comment by jiazhiqiang1977** [comment]
确实使用ChatOpenAI就可以啦，非常感谢！
