### ISSUE TITLE
4o mini免费版每天调用次数上限是3还是200

### ISSUE THREAD

**Issue by a793816354** [chatanywhere/GPT_API_free#312]
用Python调gpt-3.5-turbo没有问题，model传gpt-4o-mini调用三次之后再调用就返回429，表示达到三次上限。免费版4o mini的每日上限是3还是200

**Comment by chatanywhere** [comment]
gpt-4o-mini是200次 你是不是用的gpt-4或者gpt-4o呀 那个是3次

**Comment by chatanywhere** [comment]
试了一下确实没有问题的哦 估计你用错模型了

**Comment by a793816354** [comment]
> 试了一下确实没有问题的哦 估计你用错模型了
确实用错模型了，感谢👍
