### ISSUE TITLE
request failed with status code 401

### ISSUE THREAD

**Issue by ssyyww12123** [chatanywhere/GPT_API_free#319]
申请了免费API后，报错request failed with status code 401

**Comment by ynpl** [comment]
没改api地址吧! 用的还是openai的api!

**Comment by ssyyww12123** [comment]
> 没改api地址吧! 用的还是openai的api!
地址不是这个吗？https://api.openai.com

**Comment by ynpl** [comment]
不是 请仔细看文档哦

**Comment by ssyyww12123** [comment]
> 不是 请仔细看文档哦

好的，谢谢，刚刚看到，可以用了，多谢

**Comment by ynpl** [comment]
好的 记得关闭isuess哦
