### ISSUE TITLE
403报错

### ISSUE THREAD

**Issue by Laohu81** [chatanywhere/GPT_API_free#320]
“error”:{“message”:“免费API限制使用gpt-3.5-turbo，gpt-4 和 embeddings模型，如有更多需求，请访问 https://buyca.tech 购买付费API。The free account is limited to use gpt-3.5-turbo, gpt-4 and embeddings. If you have additional requirements, please visit https://buyca.tech to purchase a premium key.”,“type”:“chatanywhere_error”,“param”:null,“code”:“403 FORBIDDEN”}}
如果是网络问题，建议优化网络，比如打开/切换代理等。
![截图_20241108180849](https://github.com/user-attachments/assets/86dac635-8ab2-487a-b2e5-f4eb29557983)

**Comment by chatanywhere** [comment]
url少了个chat 可以仔细看下文档哈

**Comment by ynpl** [comment]
你更新一下新版本的zoteo-gpt试试,他今天下午更新的版本多了一个 选择baseURL和fullURL的.有群友反馈你这个问题. 可能他这版本有bug, 然后晚上我试的时候下载新版本已经没那个选项了.可能又更新了一版我现在的版本是1.4.2

**Comment by Laohu81** [comment]
看到邮件了，成功了，谢谢

**Comment by Laohu81** [comment]
看到了，谢谢。还是看图方便快一些，另外，我的本地版本已经显示的是1.6了，不是1.4.
&nbsp;







胡肖一

重庆开放大学&nbsp;重庆工商职业学院/城市建设工程学院

15922795735

重庆市九龙坡区九龙科技园华龙大道1号




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "ynpl"; 
Date: 2024年11月8日(星期五) 晚上10:30
To: "chatanywhere/GPT_API_free"; 
Cc: "胡肖一"; "Author"; 
Subject: Re: [chatanywhere/GPT_API_free] 403报错 (Issue #320)

&nbsp;


 
image.png (view on web)
 可以这样设置
 选择 Full API 输入框中输入https://api.chatanywhere.tech/v1/chat/completions然后其他的看图设置
