### ISSUE TITLE
[Enhancement] 403提示返回当前正在使用的模型

### ISSUE THREAD

**Issue by liangyuanpeng** [chatanywhere/GPT_API_free#328]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

我正在通过spring ai尝试调用openai API,但返回了错误,对于框架使用者来说可能不清楚正在使用的模型,如果错误信息中可以携带这个信息就太好了! 

```
org.springframework.ai.retry.NonTransientAiException: 403 - {"error":{"message":"免费API限制使用gpt-3.5-turbo，gpt-4 和 embeddings模型，如有更多需求，请访问 https://buyca.tech 购买付费API。The free account is limited to use gpt-3.5-turbo, gpt-4 and embeddings. If you have additional requirements, please visit https://buyca.tech to purchase a premium key.","type":"chatanywhere_error","param":null,"code":"403 FORBIDDEN"}}

```

**Describe alternatives you've considered**

**Additional context**

**Comment by ynpl** [comment]
![image](https://github.com/user-attachments/assets/ba46ec63-a3b5-4d29-9315-5ba79d96db66)
配置文件中可以看见吧
https://zhuanlan.zhihu.com/p/692476648

**Comment by liangyuanpeng** [comment]
是的，实际情况是我已经配置了,使用的就是gpt-3.5-turbo ,但API仍然报错 （:

**Comment by ynpl** [comment]
这种问题建议您询问程序开发者, 给他们发工单问都需要使用了什么模型. 还有问一下他们你这样设置是否正确

**Comment by chatanywhere** [comment]
没有看到你的代码，我只能猜测应该是接口用错了吧 应该用chatCompletion接口而不是completion接口

**Comment by liangyuanpeng** [comment]
感谢回复，我通过 curl 确认了APIKEY 没有问题
