### ISSUE TITLE
烦请更新一下镜像ChatGPT-Next-Web版本

### ISSUE THREAD

**Issue by slp1009** [chatanywhere/GPT_API_free#33]
当前镜像https://chatapi.chatanywhere.com.cn/的ChatGPT-Next-Web仍为老版本，ChatGPT-Next-Web已更新到v2.7，支持选择聊天内容条目截图分享，使用更加方便。烦请升级更新一下，谢谢。

ChatGPT-Next-Web最新版本：https://github.com/Yidadaa/ChatGPT-Next-Web/releases/tag/v2.7

**Comment by chatanywhere** [comment]
已更新
