### ISSUE TITLE
JetBrain插件EasyCode

### ISSUE THREAD

**Issue by nogodnodevil** [chatanywhere/GPT_API_free#333]
在JetBrain中最新版的插件EasyCode已经找不到Readme中出现的配置入口“安装好插件后在Settings > Tools > OpenAI > GPT 3.5 Turbo中如图所示配置好插件。”

**Comment by ynpl** [comment]
他应该是更新啦 已经不行了, 你可以搜gpt 然后挨个试试 哪个插件能修改api地址 就可以用

**Comment by nogodnodevil** [comment]
> 他应该是更新啦 已经不行了, 你可以搜gpt 然后挨个试试 哪个插件能修改api地址 就可以用

确实，我看EasyCode更新日志里写了，把这个模块去掉了。
