### ISSUE TITLE
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'

### ISSUE THREAD

**Issue by MarkLo127** [chatanywhere/GPT_API_free#336]

**Comment by MarkLo127** [comment]
沒事了，傳錯地方，抱歉

**Comment by ynpl** [comment]
![617d32051d5ed9fdb66b82e047dbbd38](https://github.com/user-attachments/assets/7dcd7fbd-7226-471c-90cf-78dee9ad94e9)

**Comment by AlisonDexter** [comment]
解决了吗？我也遇到这个问题，把openai版本更新后才出现这个问题

**Comment by ynpl** [comment]
这个不是api的报错, 应该是代码的问题, 建议检查一下代码
