### ISSUE TITLE
Claude API 突然变成默认语言中文了，做了什么变更吗？

### ISSUE THREAD

**Issue by aaaAlexanderaaa** [chatanywhere/GPT_API_free#340]
**Describe the bug 描述bug**

Why did the Claude API suddenly switch to defaulting to Chinese? 

Claude API 今天突然变成默认语言中文了，让它share了一下context，它说前面有个prompt让它用中文。
现在我用了system 或者在context要求它用英文都没用。

昨天还是正常工作的。

**To Reproduce 复现方法**

No special action was taken.

**Screenshots 截图**

![image](https://github.com/user-attachments/assets/4f7dbd7c-afdc-4ab3-bf50-6bae9b5533df)

<img width="1356" alt="image" src="https://github.com/user-attachments/assets/85e7eb02-ada5-48f9-831d-628ff1db09b9" />

<img width="1352" alt="image" src="https://github.com/user-attachments/assets/fbe4a5f2-22ff-43f3-90d2-df55366440e6" />

<img width="1361" alt="image" src="https://github.com/user-attachments/assets/076e1c5f-65eb-48c3-bf4c-09951e424265" />

**Tools or Programming Language 使用的工具或编程语言**

shell
curl

**Additional context 其他内容**

Nothing special.

**Comment by aaaAlexanderaaa** [comment]
![image](https://github.com/user-attachments/assets/ecd8444b-4056-405b-997a-1fb76735fe1f)

看起来是后端模型也换了

**Comment by chatanywhere** [comment]
claude由第三方渠道商提供，那边反馈说已经恢复了

**Comment by wwfcnu** [comment]
claude额度有多少呢
