### ISSUE TITLE
Langchain接口报错500

### ISSUE THREAD

**Issue by StuartXuJian** [chatanywhere/GPT_API_free#35]
apibase也改了，key也放了。测试直接用POST是可以通的。
chat = ChatOpenAI(streaming=True, callbacks=[StreamingStdOutCallbackHandler()], temperature=1, openai_api_base=openai_endpoint, openai_api_key=”sk-xxxxxx“)

调用结果失败，貌似是被转发服务器拒绝了
[chain/error] [1:llm:ChatOpenAI] [32.17s] Chain run errored with error:
"APIError(message=\"HTTP code 500 from API (Request method 'POST' not supported)\", http_status=500, request_id=None)"

**Comment by chatanywhere** [comment]
是不是api_base改的不对把

**Comment by StuartXuJian** [comment]
是的，你说对了。。我用了学院版的base放到了langchain里，它用的是openai的接口。
