### ISSUE TITLE
关于开启流式sse接收回复的消息是一整块的多行消息一起被接收。

### ISSUE THREAD

**Issue by Lemondogdog** [chatanywhere/GPT_API_free#41]
请问下像以下的两个服务器我们客户端字节通过api调用发送请求开开启stream=true 的流式回复消息请求，是不是没效果啊？支不支持sse的回传消息呢？因为使用了以下的服务器，它开启流式sse接收回复的消息是一整块的多行消息一起一次性被接收的。没有逐行接收到sse的事件发送的数据。
Host1: https://api.chatanywhere.cn (国外服务器使用)
Host2: https://api.chatanywhere.com.cn (国内中转，延时更低，推荐)

**Comment by chatanywhere** [comment]
支持sse
