### ISSUE TITLE
关于中科院版chatgpt

### ISSUE THREAD

**Issue by ZH2GitHub** [chatanywhere/GPT_API_free#43]
支持了付费api后，中科院版chatgpt的又该配置？能否一并出个教程加入快速使用文档中？

**Comment by chatanywhere** [comment]
中科院的gpt_academic在readme中有介绍

**Comment by ZH2GitHub** [comment]
> 中科院的gpt_academic在readme中有介绍
好的感谢，教程没看仔细...
