### ISSUE TITLE
GPT4忽然提示rate limit

### ISSUE THREAD

**Issue by hshenmeow** [chatanywhere/GPT_API_free#46]
用付费api时的GPT4时，在chatbox中出现这样的提示：
{"error":{"message":"Rate limit reached for default-gpt-4 in organization org-ATlb4GCUpG1s9F0EOR0L0xhf on tokens per min. Limit: 40000 / min. Please try again in 1ms. Contact us through our help center at help.openai.com if you continue to have issues.","type":"tokens","param":null,"code":null}}
但是我只是简单问了一个问题并未如提示所说有达到rate limit的行为。我试了下gpt3.5的模型都是可以的，请问是出现了什么问题呢？谢谢！

**Comment by chatanywhere** [comment]
小概率出现速率问题的话，可以暂时使用gpt-4-0314模型
