### ISSUE TITLE
我购买的api可以用在这个wechat上吗

### ISSUE THREAD

**Issue by xiangfeigao** [chatanywhere/GPT_API_free#47]
见到一个开源；https://github.com/zhayujie/chatgpt-on-wechat

我能否用购买的api用在这个项目上，
代理地址是api.chatanywhere.com.cn:443这样对吗？？？

好希望能成功，希望 回复一下

**Comment by chatanywhere** [comment]
修改代理地址是不行的，具体怎么该问下开源项目的作者吧
