### ISSUE TITLE
CORS web-browser error

### ISSUE THREAD

**Issue by SacadM** [chatanywhere/GPT_API_free#55]
Hello,

Using reverse proxy on web applications has started returning errors regarding "POST" requests. Here is an example of a console output:

Access to XMLHttpRequest at 'https://api.chatanywhere.cn//chat/completions' from origin '{...}' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

Note: I have redacted the name of the website I use the API for (for personal reason), though if more detail is required I could try to provide it.

Is this an issue on the end of the website I am trying to access? I am not certain because previously (earlier today and the past few days), accessing web applications using the reverse proxy has worked perfectly fine. Moreover, the redacted website was one of these websites that had worked fine for me.

I have confirmed the API otherwise works on other applications (Such as Microsoft Visual Studio Code), but accessing these web applications is also an important part of what I'm seeking.

Thanks in advance for your help.

**Comment by chatanywhere** [comment]
The issue has been resolved.
