### ISSUE TITLE
api.chatanywhere.com.cn 好像崩掉了

### ISSUE THREAD

**Issue by DeepTiming** [chatanywhere/GPT_API_free#57]

**Comment by chatanywhere** [comment]
。。。。。。。。。。。。。。。。。。。。。。。。
系统没有问题，请提供具体错误

**Comment by DeepTiming** [comment]
![image](https://github.com/chatanywhere/GPT_API_free/assets/38682323/3b1e456e-cf24-4e69-89a0-ab5a34fa1540)
换用api.chatanywhere.cn就是OK的

**Comment by DeepTiming** [comment]
![image](https://github.com/chatanywhere/GPT_API_free/assets/38682323/76a12332-5fc3-4de2-9a75-f1b00252fb36)
上面的没办法访问，下面的就可以

**Comment by chatanywhere** [comment]
检查你的网络是不是开了代理之类的，系统可正常访问
