### ISSUE TITLE
请问转发API是否支持openai embedding

### ISSUE THREAD

**Issue by jarheadjoe** [chatanywhere/GPT_API_free#58]
付费转发api是否支持openai embedding
openai.Embedding.create(input=text, model="text-embedding-ada-002")
使用下来免费api key做embedding时会报错

  File "/Users/joe/opt/anaconda3/envs/dataProcesspy38/lib/python3.8/site-packages/openai/api_requestor.py", line 669, in _interpret_response_line
    if 'text/plain' in rheaders.get('Content-Type'):
TypeError: argument of type 'NoneType' is not iterable

**Comment by chatanywhere** [comment]
这边测试以下代码没有出现错误
```python
import openai

openai.api_key='sk-xxxxxxxxxx'
openai.api_base='https://api.chatanywhere.com.cn/v1'

# embeddings
embeddings = openai.Embedding.create(input=["The food was delicious and the waiter..."], model="text-embedding-ada-002")
print(embeddings)
```
