### ISSUE TITLE
领取key的网站访问不了，挂梯子也不行

### ISSUE THREAD

**Issue by MengYingjie** [chatanywhere/GPT_API_free#59]
RT

**Comment by chatanywhere** [comment]
可以试试全局代理呢

**Comment by Nvidiaction** [comment]
![image](https://github.com/chatanywhere/GPT_API_free/assets/105565794/c816ce18-3874-44b5-989d-794dc25d179d)

**Comment by chatanywhere** [comment]
下午数据库服务器被攻击，已经恢复
