### ISSUE TITLE
使用咨询

### ISSUE THREAD

**Issue by nimrod1990** [chatanywhere/GPT_API_free#6]
我想在 gpt-academic 项目中使用你的 key，请教一下怎么设置 API 转发？

**Comment by chatanywhere** [comment]
gpt-academic应该也是用的openai官方库，参照教程改环境变量即可

**Comment by nimrod1990** [comment]
我在 huggingface 中部署，是不是修改 config.py中的以下内容即可？
# 重新URL重新定向，实现更换API_URL的作用（常规情况下，不要修改!!）
  | # （高危设置！通过修改此设置，您将把您的API-KEY和对话隐私完全暴露给您设定的中间人！）
  | # 格式 {"https://api.openai.com/v1/chat/completions": "在这里填写重定向的api.openai.com的URL"}
  | # 例如 API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://ai.open.com/api/conversation"}
  | API_URL_REDIRECT = {"https://api.chatanywhere.cn/v1/chat/completions": "https://api.chatanywhere.cn"}

**Comment by chatanywhere** [comment]
```
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://api.chatanywhere.cn/v1/chat/completions"}
```
应该是这样吧

**Comment by nimrod1990** [comment]
谢谢你的帮助～

**Comment by nimrod1990** [comment]
可否添加对开源项目[ChatPaper](https://github.com/kaixindelele/ChatPaper)的支持？
需要如何在源码中修改反向代理？

**Comment by nimrod1990** [comment]
# Set OPENAI_API_BASE environment variable
os.environ["OPENAI_API_BASE"] = "https://api.chatanywhere.cn/v1"

> 简单看了一下 他应该用的也是官方openai库 参照教程改环境变量即可
