### ISSUE TITLE
使用apikey时报错401

### ISSUE THREAD

**Issue by copi143** [chatanywhere/GPT_API_free#62]
Server Error: Request failed with status code 401 and body {"error":{"message":"Incorrect API key provided: sk-VKMIs***************************************wjh3. You can find your API key at https://platform.openai.com/account/api-keys.","type":"invalid_request_error","param":null,"code":"invalid_api_key"}}Server Error: Request failed with status code 401 and body {"error":{"message":"Incorrect API key provided: sk-VKMIs***************************************wjh3. You can find your API key at https://platform.openai.com/account/api-keys.","type":"invalid_request_error","param":null,"code":"invalid_api_key"}}

**Comment by chatanywhere** [comment]
请仔细阅读 readme
