### ISSUE TITLE
limit to use gpt-3.5-turbo and embeddings

### ISSUE THREAD

**Issue by Stillily** [chatanywhere/GPT_API_free#64]
我自己写的java返回说limit to use gpt-3.5-turbo and embeddings
昨天是可以用的

            String json = "{\"model\": \"gpt-3.5-turbo\",\"stream\": true,\"messages\":[" +
                    message(content,session)+
                    "]}";

            Request request = new Request.Builder()
                    .url("https://api.chatanywhere.com.cn/v1/chat/completions")
                    .addHeader("Authorization", "Bearer sk-Wst...")
                    .post(body)
                    .build();

**Comment by HideInMatrix** [comment]
我也出现这个问题，但是我选择的是chatGPT4模型，提示也是这个

**Comment by Stillily** [comment]
> 我也出现这个问题，但是我选择的是chatGPT4模型，提示也是这个

你之前付费了吗，我最近都没改代码突然就不行了

**Comment by HideInMatrix** [comment]
> > 我也出现这个问题，但是我选择的是chatGPT4模型，提示也是这个
> 
> 你之前付费了吗，我最近都没改代码突然就不行了

你不是标注免费的吗

**Comment by Stillily** [comment]
> > > 我也出现这个问题，但是我选择的是chatGPT4模型，提示也是这个
> > 
> > 
> > 你之前付费了吗，我最近都没改代码突然就不行了
> 
> 你不是标注免费的吗

 我是免费啊，但你不是4吗，本来我这几天还在想要不要买4的

**Comment by chatanywhere** [comment]
群里有个人模型名称大写的，我处理大小写，你看看是不是这个问题，改成小写应该就可以

**Comment by Stillily** [comment]
> 群里有个人模型名称大写的，我处理大小写，你看看是不是这个问题，改成小写应该就可以

 今天试又一切正常了，代码一直都没变过
