### ISSUE TITLE
购买了api如何查询剩余额度

### ISSUE THREAD

**Issue by yj920** [chatanywhere/GPT_API_free#70]
如题，在商城没有看到有关说明

**Comment by ethanzhao2001** [comment]
其实有在本仓库readme和商品详情都有写。余额和使用记录查询（通知公告也会发在这里）: https://api.chatanywhere.cn/

**Comment by tocky0** [comment]
https://api.chatanywhere.tech/#/ 这里就可以查。申领了一个key，用了几次后，查出来剩余额度是一个 负值，这个还能用吗，有没有下限啥的，这是要充值吗？
感谢。
