### ISSUE TITLE
免费key出错

### ISSUE THREAD

**Issue by 503611908** [chatanywhere/GPT_API_free#71]
错误信息：☹️发生了错误：wrong api key

**Comment by sunrose007** [comment]
用不了  limit to use gpt-3.5-turbo and embeddings

**Comment by Hbin-Zhuang** [comment]
错误： Incorrect key provided

**Comment by CaOUMay** [comment]
在使用poai时发生错误：
Incorrect API key provided
😟

**Comment by chatanywhere** [comment]
api key不正确请检查是否正确修改了接入点 url

**Comment by chatanywhere** [comment]
> 用不了 limit to use gpt-3.5-turbo and embeddings

用法有问题，免费 key 只开了gpt-3.5-turbo 和 embedding，估计你在用 davinci 接口调用gpt模型

**Comment by 1273082756** [comment]
我也是 但是我是选了16k才报错403, 普通的不报错

**Comment by chatanywhere** [comment]
> 我也是 但是我是选了16k才报错403, 普通的不报错

免费key不再支持16K模型
