### ISSUE TITLE
api key has been suspended是被封号了吗

### ISSUE THREAD

**Issue by Lianlianlianlianlian** [chatanywhere/GPT_API_free#74]

**Comment by chatanywhere** [comment]
是的，被检测到异常行为会被系统封号。

**Comment by tohsaka888** [comment]
同`api key has been suspended`，这个封禁是OpenAI封禁的还是ChatAnyWhere封禁的？

**Comment by chatanywhere** [comment]
ChatAnywhere封禁，检查自己是否存在多人共享使用，key 泄露，免费 Key 商用等情况。

**Comment by chatanywhere** [comment]
如确认自己被误封，请QQ联系我们申诉。

**Comment by tohsaka888** [comment]
> 如确认自己被误封，请QQ联系我们申诉。

买了付费key了，问一下付费key可以开发票吗？

**Comment by chatanywhere** [comment]
> > 如确认自己被误封，请QQ联系我们申诉。
> 
> 买了付费key了，问一下付费key可以开发票吗？

商用问题请加qq群联系客服
