### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by AriesChenL** [chatanywhere/GPT_API_free#75]
API Error: 403 Forbidden

遇到了来自 OpenAI API 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，或者[点击这里查看常见问题文档](https://chatboxai.app/redirect_app/faqs/zh-Hans)。

**Comment by AriesChenL** [comment]
免费的16K不能用了

**Comment by chatanywhere** [comment]
是的

**Comment by Fenhy** [comment]
![image](https://github.com/chatanywhere/GPT_API_free/assets/16318946/9a76306a-60b2-4d40-ad06-efcf281ea6bb)
![image](https://github.com/chatanywhere/GPT_API_free/assets/16318946/d8cd3d48-2c2b-4e61-b3fa-3a91df25caae)

今天也突然用不了，试了几个模型，都不行。

**Comment by chatanywhere** [comment]
这个情况看起来是你的网络问题，你试试关掉梯子
