### ISSUE TITLE
403 foribidden

### ISSUE THREAD

**Issue by cfx2020** [chatanywhere/GPT_API_free#76]
我使用 https://github.com/mushan0x0/AI0x0.com 软件中的GPT-next-web时遇到了此问题，并且只有使用此key才有这个问题，换用别的第三方key设置转发地址之后就能使用，这是什么原因呢，开代理和不开代理都试过，两种转发地址也试过。看API文档说403是余额不足，免费的key也有余额吗？
![image](https://github.com/chatanywhere/GPT_API_free/assets/60496874/24dbac2d-fc39-493b-a008-e247fd35947c)
![image](https://github.com/chatanywhere/GPT_API_free/assets/60496874/120b7824-c002-48ea-8a63-594a1ef0968b)

```
{
  "error": true,
  "message": "Error response from https://api.chatanywhere.com.cn/v1/chat/completions: 403 Forbidden"
}
```

**Comment by chatanywhere** [comment]
免费key报错403一般可能是被系统封禁了

**Comment by chatanywhere** [comment]
免费key报错403一般是使用了不支持的模型，免费key自8月4日起不再支持16k模型。另外也可能是被系统封禁。

**Comment by cfx2020** [comment]
我知道今天起不支持16k了，使用的时候我也更换回了3.5turbo，但这个key我现在都还能在chatgptbox，zoterogpt，我自己的next-web中使用，唯独这个软件很奇怪，一直报403。
