### ISSUE TITLE
chatgpt4 无效

### ISSUE THREAD

**Issue by zema1** [chatanywhere/GPT_API_free#8]
买了30块钱那个付费的 key，试了这两个地址的返回都不是 gpt4，所以这个是假的？模型都选择了 gpt-4

https://chatapi.chatanywhere.com.cn/
![image](https://github.com/chatanywhere/GPT_API_free/assets/20637881/925c6b16-348d-4724-9d2d-aabb0d0f7733)

chatbox
![image](https://github.com/chatanywhere/GPT_API_free/assets/20637881/c4702942-c362-4839-8e09-71522d66bfef)

**Comment by chatanywhere** [comment]
你提的问题并不存在，GPT4是正常答复的
你所以为可用的测试方法是不行的，比如直接问GPT4:"你是GPT3.5还是GPT4?"一般情况下GPT4的API也会回答自己是GPT3，这是因为训练数据集只到2021年9月的原因。
区分gpt4的方法可以尝试问他以下两个问题，自行对比区别：
1. There are 9 birds in the tree, the hunter shoots one, how many birds are left in the tree？
2. 鲁迅和周树人的关系
