### ISSUE TITLE
免费key用16k模型报错

### ISSUE THREAD

**Issue by hienchu** [chatanywhere/GPT_API_free#82]
错误信息如下：
WARNING:langchain.llms.base:Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: Invalid response object from API: 'limit to use gpt-3.5-turbo and embeddings' (HTTP response code was 403).

模型初始化参数：
`ChatOpenAI(temperature=0.1, model="gpt-3.5-turbo-16k")`

**Comment by ethanzhao2001** [comment]
免费不支持16k你看readme没？

**Comment by hienchu** [comment]
看到8月6号的更新了，谢谢！
