### ISSUE TITLE
在autogpt里面直接用显示Incorrect API key provided

### ISSUE THREAD

**Issue by BBrother-GFC** [chatanywhere/GPT_API_free#85]
![image](https://github.com/chatanywhere/GPT_API_free/assets/51117375/a46b6431-58f8-478a-adea-17f0f144293d)
是有科学上网的环境的

**Comment by loukai99** [comment]
看readme啊

**Comment by fengzi679** [comment]
申请API的时候，显示不允许注册不到7天的账户关联怎么办

**Comment by chatanywhere** [comment]
> 

等7天
