### ISSUE TITLE
zotero gpt提示报错key是无效的

### ISSUE THREAD

**Issue by jackwky** [chatanywhere/GPT_API_free#88]
**Describe the bug 描述bug**
zotero gpt提示报错key是无效的

**To Reproduce 复现方法**

**Screenshots 截图**
![image](https://github.com/chatanywhere/GPT_API_free/assets/126163628/0208a989-c057-4058-8d60-f7f9e5b7c6c9)

**Additional context 其他内容**
invalid_api_key

https://api.openai.com/v1/chat/completions
invalid_request_error
Incorrect API key provided: sk-YQ8PA***************************************WCDw. You can find your API key at https://platform.openai.com/account/api-keys.

**Comment by zhdivision** [comment]
想问一下最后怎么解决了？
