### ISSUE TITLE
站点挂了

### ISSUE THREAD

**Issue by yimengfan** [chatanywhere/GPT_API_free#89]
[(https://chatapi.chatanywhere.cn/#/)](https://chatapi.chatanywhere.cn/#/)](https://chatapi.chatanywhere.cn/#/)

**Comment by chatanywhere** [comment]
该站点国内无法使用

**Comment by BlackBerry009** [comment]
> 该站点国内无法使用

挂了vpn不行了，应该转发挂了

**Comment by yimengfan** [comment]
> 该站点国内无法使用

挂了vpn的，本来好好的 突然就挂了
