### ISSUE TITLE
chatgpt4 无效

### ISSUE THREAD

**Issue by zema1** [chatanywhere/GPT_API_free#9]
上个问题还没解决，怎么就 close 了。 related to: https://github.com/chatanywhere/GPT_API_free/issues/8  

我去openai 官网问了一下同样的问题，结果如下：

![lQLPJxm8OkiVG8bNATrNAtCwnwDsU8mMtJIEWm8fS4AMAA_720_314](https://github.com/chatanywhere/GPT_API_free/assets/20637881/6b0ed1d1-30ed-40f7-b1c8-de431ce1b920)

我是用 poe.com 每天一次的 chatgpt4 问同样的问题：
![image](https://github.com/chatanywhere/GPT_API_free/assets/20637881/5cc75d63-ce74-4ef6-b588-17faf19aaa79)

这个怎么解释

**Comment by chatanywhere** [comment]
我解释的已经很清楚了，API就是这样，真的假不了假的真不了，唯一的鉴别方法：通过问题测试，测试问题已经给你了，你自行测试，你也可以自己去搜测试问题。另外你这个问题，通过加前置prompt，甚至可以让gpt3.5回答自己是GPT5，你是不是觉得他就是GPT5了呢？

**Comment by zema1** [comment]
OK 我再找一些实际的问题试下
