### ISSUE TITLE
https://api.chatanywhere.cn这个域名无法使用

### ISSUE THREAD

**Issue by MrGongqi** [chatanywhere/GPT_API_free#91]
你好，国外中转无法使用了
https://api.chatanywhere.cn这个域名使用时报错：
![image](https://github.com/chatanywhere/GPT_API_free/assets/49467246/8e43759d-353e-4a93-bf9c-7170335d1ed5)

**Comment by chatanywhere** [comment]
该域名已经全面屏蔽国内ip

**Comment by MrGongqi** [comment]
我也是刚才才发现，将代理变成全局代理后就没有出问题了
