### ISSUE TITLE
有没有办法可以将openai重定向到chatanywhere？

### ISSUE THREAD

**Issue by LAWArthur** [chatanywhere/GPT_API_free#92]
如题，因为有些用到chatgpt的程序的请求地址是写死在程序里的，我希望能够通过全局代理将openai的流量转发到chat anywhere。
我尝试了mitmproxy，但一直都会报502 sslv3警告，不知道有没有人做过类似的尝试可以提供一些帮助。

**Comment by loukai99** [comment]
一个不成熟的想法，nginx做api.openai.com的自签名证书，然后反向代理，反代到chatanywhere，然后本地hosts吧api.openai.com域名解析到你的服务器。当然这些的前提是你的程序不做严格证书验证，能用不可信的证书。
