### ISSUE TITLE
使用academic出现非OpenAI官方接口返回了错误:wrong api key

### ISSUE THREAD

**Issue by 564192234** [chatanywhere/GPT_API_free#93]
**Describe the bug 描述bug**
使用academic出现非OpenAI官方接口返回了错误:wrong api key，请问是我哪错了，需要怎么解决，麻烦了。

**To Reproduce 复现方法**
1.安装好环境，配置了环境，获取了api_key,按照对应更改了API_URL_REDIRECT，进入academic，发送问题出现截图内报错

**Screenshots 截图**
![image](https://github.com/chatanywhere/GPT_API_free/assets/73697191/da38a8a5-d5d2-4fee-9579-48611c680db0)
![image](https://github.com/chatanywhere/GPT_API_free/assets/73697191/6e662738-2455-4985-8674-af884874f37c)

**Tools or Programming Language 使用的工具或编程语言**
python
.

**Comment by Skye601** [comment]
请问你是怎么解决的这个问题的啊？

**Comment by angus-lu** [comment]
可能是API_URL_REDIRECT的value用错了，非官方的接口可能和教程上给的不一样，可以再问一下，我这边也遇到了这个问题，修改之后成功运行了。

**Comment by qunkery** [comment]
请问怎么解决的？
