### ISSUE TITLE
为什么用whisper，指定返回srt文件还是会返回txt文件，且有10M大小限制（官方限制为25M）

### ISSUE THREAD

**Issue by jian53286** [chatanywhere/GPT_API_free#96]
**Describe the bug 描述bug**
为什么用whisper，response_format="srt",指定返回srt文件还是会返回txt文件
且有10M大小限制（官方限制为25M），这不够用

**To Reproduce 复现方法**
import openai
openai.api_base = "https://api.chatanywhere.com.cn/v1/"

transcript = openai.Audio.transcribe("whisper-1", audio_file, prompt=prompt,response_format="srt",language="en")

**Tools or Programming Language 使用的工具或编程语言**
python

**Comment by chatanywhere** [comment]
大小限制已修改为25M，srt支持之前未考虑，暂时没有适配
