### ISSUE TITLE
The gateway did not receive a timely response from the upstream server or application

### ISSUE THREAD

**Issue by WolveStorm** [chatanywhere/GPT_API_free#97]
**Describe the bug 描述bug**
可能在使用时，gpt会返回一个较长的文本，此时就会超时

**Comment by WolveStorm** [comment]
openai.error.APIError: HTTP code 504 from API (<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<h1>504 Gateway Time-out</h1>
<p>The gateway did not receive a timely response from the upstream server or application.<hr/>Powered by Tengine</body>
</html>

**Comment by chatanywhere** [comment]
http 300s超时了 长文本建议使用流传输
