### ISSUE TITLE
请求支持最新推出的gpt-3.5-turbo-instruct

### ISSUE THREAD

**Issue by jian53286** [chatanywhere/GPT_API_free#98]

**Comment by chatanywhere** [comment]
应该是直接就支持的吧

**Comment by jian53286** [comment]
并没有支持，使用python无法调用

**Comment by chatanywhere** [comment]
![image](https://github.com/chatanywhere/GPT_API_free/assets/111742565/2328c290-49da-4861-8bed-b947c2e48a4c)
这边测试确实没有问题

**Comment by miaonia** [comment]
免费版不支持吧，收费版我试了可以，免费版响应：limit to use gpt-3.5-turbo and embeddings
